#!/usr/bin/env python3
"""批量添加 team_name_mapping.json 中缺失的英文→中文队名映射（修复版，不覆盖已有中文条目）"""
import json, os, unicodedata as ud

MAPPING_PATH = '/root/data/team_name_mapping.json'

def norm(s):
    s = ud.normalize('NFKD', s or '')
    s = s.encode('ascii', 'ignore').decode('ascii')
    s = s.lower().replace(' & ', ' and ').replace('&', ' and ').replace('  ', ' ').strip()
    return s

# 加载现有映射
with open(MAPPING_PATH, encoding='utf-8') as f:
    mapping = json.load(f)

# 构建 en_to_cn 查找表（用于去重）
en_to_cn = {}
cn_keys = set()  # 所有已存在的中文键
for k, v in mapping.items():
    k_stripped = k.strip()
    v_stripped = v.strip()
    is_cn = any('\u4e00' <= c <= '\u9fff' for c in k_stripped)
    cn_keys.add(k_stripped)
    if is_cn:
        en_clean = norm(v_stripped).replace(' ', '')
        if en_clean not in en_to_cn:
            en_to_cn[en_clean] = k_stripped
    else:
        en_key = norm(k_stripped).replace(' ', '')
        if en_key not in en_to_cn:
            en_to_cn[en_key] = v_stripped

def key_for(en_name):
    return norm(en_name).replace(' ', '')

def add(en_name, cn_name):
    """添加映射，如果已存在或会覆盖则跳过"""
    k = key_for(en_name)
    if k in en_to_cn:
        return False  # 英文→中文映射已存在
    if cn_name in cn_keys:
        return False  # 中文键已存在，不覆盖
    mapping[cn_name] = en_name
    en_to_cn[k] = cn_name
    cn_keys.add(cn_name)
    return True

added = 0

# ============ 只有首次缺失的团队（不覆盖已有中文条目） ============
entries = [
    # -- 国家队 --
    ("Côte d'Ivoire", "科特迪瓦"),
    ("China", "中国"),
    ("Cambodia", "柬埔寨"),
    ("Myanmar", "缅甸"),
    ("Benin", "贝宁"),
    ("Lesotho", "莱索托"),
    ("Sierra Leone", "塞拉利昂"),
    ("Andorra", "安道尔"),
    ("San Marino", "圣马力诺"),
    ("Liechtenstein", "列支敦士登"),
    ("Afghanistan", "阿富汗"),
    ("Kenya", "肯尼亚"),
    ("Maldives", "马尔代夫"),
    ("Ireland", "爱尔兰"),
    ("Tanzania", "坦桑尼亚"),
    ("Mauritania", "毛里塔尼亚"),
    ("Liberia", "利比里亚"),
    ("Zimbabwe", "津巴布韦"),
    ("Madagascar", "马达加斯加"),
    ("Comoros", "科摩罗"),
    ("Somalia", "索马里"),
    ("Mozambique", "莫桑比克"),
    ("Botswana", "博茨瓦纳"),
    ("Rwanda", "卢旺达"),
    ("Uganda", "乌干达"),
    ("Ethiopia", "埃塞俄比亚"),
    ("Sudan", "苏丹"),
    ("South Sudan", "南苏丹"),
    ("Central African Republic", "中非"),
    ("Chad", "乍得"),
    ("Niger", "尼日尔"),
    ("Burkina Faso", "布基纳法索"),
    ("Togo", "多哥"),
    ("Seychelles", "塞舌尔"),
    ("Mauritius", "毛里求斯"),
    ("Djibouti", "吉布提"),
    ("Eritrea", "厄立特里亚"),
    ("Eswatini", "斯威士兰"),
    ("Malawi", "马拉维"),
    ("São Tomé and Príncipe", "圣多美和普林西比"),
    ("Cabo Verde", "佛得角"),
    ("Gambia", "冈比亚"),
    ("Oman", "阿曼"),
    ("Yemen", "也门"),
    ("Bahrain", "巴林"),
    ("Kuwait", "科威特"),
    ("Syria", "叙利亚"),
    ("Palestine", "巴勒斯坦"),
    ("Mongolia", "蒙古"),
    ("Brunei", "文莱"),
    ("Timor-Leste", "东帝汶"),
    ("Bhutan", "不丹"),
    ("Nepal", "尼泊尔"),
    ("Sri Lanka", "斯里兰卡"),
    ("Chinese Taipei", "中华台北"),
    ("Macau", "中国澳门"),
    ("Guam", "关岛"),
    ("Northern Mariana Islands", "北马里亚纳群岛"),
    ("Cook Islands", "库克群岛"),
    ("Tahiti", "塔希提"),
    ("New Caledonia", "新喀里多尼亚"),
    ("Vanuatu", "瓦努阿图"),
    ("Solomon Islands", "所罗门群岛"),
    ("Samoa", "萨摩亚"),
    ("American Samoa", "美属萨摩亚"),
    ("Papua New Guinea", "巴布亚新几内亚"),
    ("Cuba", "古巴"),
    ("Puerto Rico", "波多黎各"),
    ("Martinique", "马提尼克"),
    ("Guadeloupe", "瓜德罗普"),
    ("French Guiana", "法属圭亚那"),
    ("Guyana", "圭亚那"),
    ("Suriname", "苏里南"),
    ("Belize", "伯利兹"),
    ("Nicaragua", "尼加拉瓜"),
    ("Dominica", "多米尼克"),
    ("Saint Kitts and Nevis", "圣基茨和尼维斯"),
    ("Antigua and Barbuda", "安提瓜和巴布达"),
    ("Montserrat", "蒙特塞拉特"),
    ("Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯"),
    ("Grenada", "格林纳达"),
    ("Saint Lucia", "圣卢西亚"),
    ("Barbados", "巴巴多斯"),
    ("Bermuda", "百慕大"),
    ("Cayman Islands", "开曼群岛"),
    ("Turks and Caicos Islands", "特克斯和凯科斯群岛"),
    ("Bahamas", "巴哈马"),
    ("Malta", "马耳他"),
    ("Gibraltar", "直布罗陀"),
    ("Faroe Islands", "法罗群岛"),
    ("Luxembourg", "卢森堡"),
    ("Zambia", "赞比亚"),
    ("Bangladesh", "孟加拉国"),
    ("Guatemala", "危地马拉"),
    ("Dominican Republic", "多米尼加"),
    ("El Salvador", "萨尔瓦多"),
    ("Honduras", "洪都拉斯"),
    ("Costa Rica", "哥斯达黎加"),
    ("Jamaica", "牙买加"),
    ("Trinidad and Tobago", "特立尼达和多巴哥"),
    ("Venezuela", "委内瑞拉"),
    ("Bolivia", "玻利维亚"),
    ("Paraguay", "巴拉圭"),
    ("Uruguay", "乌拉圭"),
    ("Ecuador", "厄瓜多尔"),
    ("Peru", "秘鲁"),
    ("Chile", "智利"),
    ("Colombia", "哥伦比亚"),
    ("New Zealand", "新西兰"),
    ("Iceland", "冰岛"),
    ("Russia", "俄罗斯"),
    ("Ukraine", "乌克兰"),
    ("Belarus", "白俄罗斯"),
    ("Montenegro", "黑山"),
    ("Albania", "阿尔巴尼亚"),
    ("North Macedonia", "北马其顿"),
    ("Kosovo", "科索沃"),
    ("Moldova", "摩尔多瓦"),
    ("Cyprus", "塞浦路斯"),
    ("Azerbaijan", "阿塞拜疆"),
    ("Armenia", "亚美尼亚"),
    ("Georgia", "格鲁吉亚"),
    ("Kazakhstan", "哈萨克斯坦"),
    ("Kyrgyzstan", "吉尔吉斯斯坦"),
    ("Tajikistan", "塔吉克斯坦"),
    ("Turkmenistan", "土库曼斯坦"),
    ("Uzbekistan", "乌兹别克斯坦"),
    ("Lebanon", "黎巴嫩"),
    ("Jordan", "约旦"),
    ("Israel", "以色列"),
    ("Thailand", "泰国"),
    ("Vietnam", "越南"),
    ("Indonesia", "印度尼西亚"),
    ("Malaysia", "马来西亚"),
    ("Singapore", "新加坡"),
    ("Philippines", "菲律宾"),
    ("India", "印度"),
    ("Pakistan", "巴基斯坦"),
    ("Maldives", "马尔代夫"),
    ("Myanmar", "缅甸"),
    ("Qatar", "卡塔尔"),
    ("United Arab Emirates", "阿联酋"),
    ("Saudi Arabia", "沙特阿拉伯"),
    ("Oman", "阿曼"),
    ("Bahrain", "巴林"),
    ("Kuwait", "科威特"),
    ("Syria", "叙利亚"),
    ("Yemen", "也门"),
    ("Iraq", "伊拉克"),
    ("Iran", "伊朗"),
    ("Afghanistan", "阿富汗"),
    ("Turkmenistan", "土库曼斯坦"),
    ("Mongolia", "蒙古"),
    ("North Korea", "朝鲜"),
    ("Djibouti", "吉布提"),
    ("Eritrea", "厄立特里亚"),
    ("Ethiopia", "埃塞俄比亚"),
    ("Sudan", "苏丹"),
    ("South Sudan", "南苏丹"),
    ("Central African Rep.", "中非"),
    ("Chad", "乍得"),
    ("Niger", "尼日尔"),
    ("Mali", "马里"),
    ("Burkina Faso", "布基纳法索"),
    ("Senegal", "塞内加尔"),
    ("Gambia", "冈比亚"),
    ("Guinea", "几内亚"),
    ("Guinea-Bissau", "几内亚比绍"),
    ("Sierra Leone", "塞拉利昂"),
    ("Liberia", "利比里亚"),
    ("Côte d'Ivoire", "科特迪瓦"),
    ("Ghana", "加纳"),
    ("Togo", "多哥"),
    ("Benin", "贝宁"),
    ("Nigeria", "尼日利亚"),
    ("Cameroon", "喀麦隆"),
    ("Equatorial Guinea", "赤道几内亚"),
    ("Gabon", "加蓬"),
    ("Congo", "刚果"),
    ("DR Congo", "刚果民主共和国"),
    ("Angola", "安哥拉"),
    ("South Africa", "南非"),
    ("Namibia", "纳米比亚"),
    ("Botswana", "博茨瓦纳"),
    ("Zimbabwe", "津巴布韦"),
    ("Mozambique", "莫桑比克"),
    ("Malawi", "马拉维"),
    ("Zambia", "赞比亚"),
    ("Tanzania", "坦桑尼亚"),
    ("Rwanda", "卢旺达"),
    ("Burundi", "布隆迪"),
    ("Uganda", "乌干达"),
    ("Kenya", "肯尼亚"),
    ("Somalia", "索马里"),
    ("Comoros", "科摩罗"),
    ("Mauritius", "毛里求斯"),
    ("Seychelles", "塞舌尔"),
    ("Cape Verde", "佛得角"),
    ("Mauritania", "毛里塔尼亚"),
    ("Madagascar", "马达加斯加"),
    ("Lesotho", "莱索托"),
    ("Eswatini", "斯威士兰"),
    ("Papua New Guinea", "巴布亚新几内亚"),
    ("Fiji", "斐济"),
    ("Solomon Islands", "所罗门群岛"),
    ("Vanuatu", "瓦努阿图"),
    ("Samoa", "萨摩亚"),
    ("Tonga", "汤加"),
    ("Cook Islands", "库克群岛"),
    ("Tahiti", "塔希提"),
    ("New Caledonia", "新喀里多尼亚"),
    # -- 巴西 --
    ("Sport Recife", "累西腓体育"),
    ("Criciúma", "克里西乌马"),
    ("Londrina", "隆德里纳"),
    ("Novorizontino", "诺沃里宗蒂诺"),
    ("Botafogo-SP", "博塔弗戈SP"),
    ("Cuiabá", "库亚巴"),
    ("Juventude", "青年人"),
    ("Goiás", "戈亚斯"),
    ("Ceará", "塞阿拉"),
    ("Náutico", "瑙蒂科"),
    ("Ponte Preta", "蓬特普雷塔"),
    ("CRB", "CRB"),
    ("Vila Nova FC", "维拉诺瓦"),
    ("América Mineiro", "米内罗美洲"),
    ("Operário-PR", "奥佩拉里奥PR"),
    ("Paysandu SC", "派桑杜"),
    ("Remo", "雷莫"),
    ("Cruzeiro", "克鲁塞罗"),
    ("Vasco da Gama", "瓦斯科达伽马"),
    ("Palmeiras", "帕尔梅拉斯"),
    ("Red Bull Bragantino", "布拉甘蒂诺红牛"),
    ("Santos", "桑托斯"),
    ("Bahia", "巴伊亚"),
    ("Grêmio", "格雷米奥"),
    ("Avaí", "阿瓦伊"),
    ("Athletico", "巴拉纳竞技"),
    ("Flamengo", "弗拉门戈"),
    ("Corinthians", "科林蒂安"),
    ("Fluminense", "弗卢米嫩塞"),
    ("Atlético Mineiro", "米内罗竞技"),
    ("São Paulo", "圣保罗"),
    ("Coritiba", "科里蒂巴"),
    ("Chapecoense", "沙佩科人"),
    ("Botafogo", "博塔弗戈"),
    ("Internacional", "国际(巴西)"),
    ("Vitória", "维多利亚"),
    ("Mirassol", "米拉索尔"),
    ("Atlético Goianiense", "戈亚尼恩斯竞技"),
    ("Fortaleza", "福塔雷萨"),
    ("Confiança", "孔菲安萨"),
    ("Jacuipense", "雅库伊彭塞"),
    ("São Bernardo", "圣贝尔纳多"),
    ("Barra FC", "巴拉FC"),
    ("Bragantino", "布拉甘蒂诺"),
    ("América-RN", "美洲RN"),
    ("Santa Cruz", "圣克鲁斯"),
    ("Volta Redonda", "沃尔塔雷东达"),
    ("ABC FC", "ABC"),
    ("Treze", "特雷泽"),
    ("Ypiranga-RS", "伊皮兰加RS"),
    ("Esportivo", "埃斯波尔蒂沃"),
    ("Portuguesa RJ", "葡萄牙人RJ"),
    ("Ferroviário", "费罗维亚里奥"),
    ("Sampaio Corrêa", "桑帕约科雷亚"),
    ("Altos", "阿尔托斯"),
    ("Floresta EC", "弗洛雷斯塔"),
    ("Tombense", "通本塞"),
    ("Ituano", "伊图阿诺"),
    ("Brusque", "布鲁斯克"),
    ("Chapecoense-SC", "沙佩科人SC"),
    ("Marcílio Dias", "马西利奥迪亚斯"),
    ("Hercílio Luz", "埃尔西利奥卢斯"),
    # -- 日本 --
    ("Oita Trinita", "大分三神"),
    ("Fukushima United FC", "福岛联"),
    ("Zweigen Kanazawa", "金泽塞维根"),
    ("Blaublitz Akita", "秋田蓝色闪电"),
    ("Tochigi SC", "枥木SC"),
    ("Tokushima Vortis", "德岛漩涡"),
    ("Vanraure Hachinohe", "八户南乡"),
    ("Sagan Tosu", "鸟栖砂岩"),
    ("Kawasaki Frontale", "川崎前锋"),
    ("Kashiwa Reysol", "柏太阳神"),
    ("Yokohama F. Marinos", "横滨水手"),
    ("Jubilo Iwata", "磐田喜悦"),
    ("Urawa Red Diamonds", "浦和红钻"),
    ("Tokyo Verdy", "东京绿茵"),
    ("FC Gifu", "岐阜FC"),
    ("Mito Hollyhock", "水户蜀葵"),
    ("Machida Zelvia", "町田泽维亚"),
    ("SC Sagamihara", "相模原SC"),
    ("Fujieda MYFC", "藤枝MYFC"),
    ("Albirex Niigata", "新潟天鹅"),
    ("Yokohama FC", "横滨FC"),
    ("RB Omiya Ardija", "大宫松鼠RB"),
    ("Matsumoto Yamaga FC", "松本山雅"),
    ("Tochigi City FC", "栃木市FC"),
    ("Tegevajaro Miyazaki", "宫崎棒牛鸟"),
    ("Vegalta Sendai", "仙台七夕"),
    ("JEF United Chiba", "千叶市原"),
    ("FC Tokyo", "东京FC"),
    ("Kashima Antlers", "鹿岛鹿角"),
    ("Fagiano Okayama", "冈山绿雉"),
    ("Shimizu S-Pulse", "清水心跳"),
    ("FC Imabari", "今治FC"),
    ("Montedio Yamagata", "山形山神"),
    ("Thespa Gunma", "群马草津温泉"),
    ("Gamba Osaka", "大阪钢巴"),
    ("Avispa Fukuoka", "福冈黄蜂"),
    ("Ehime FC", "爱媛FC"),
    ("Cerezo Osaka", "大阪樱花"),
    ("Nagoya Grampus", "名古屋鲸八"),
    ("Sanfrecce Hiroshima", "广岛三箭"),
    ("Shonan Bellmare", "湘南比马"),
    ("Kochi United SC", "高知联"),
    ("FC Osaka", "大阪FC"),
    ("Nara Club", "奈良俱乐部"),
    ("Vissel Kobe", "神户胜利船"),
    ("Kyoto Sanga FC", "京都不死鸟"),
    ("Kataller Toyama", "富山胜利"),
    ("V-Varen Nagasaki", "长崎航海"),
    ("FC Ryukyu", "琉球FC"),
    ("Reilac Shiga FC", "瑞拉滋贺"),
    ("Kagoshima United", "鹿儿岛联"),
    ("Iwaki FC", "磐城FC"),
    ("Ventforet Kofu", "甲府风林"),
    ("Roasso Kumamoto", "熊本深红"),
    ("AC Nagano Parceiro", "长野伙伴"),
    ("Renofa Yamaguchi FC", "山口雷诺法"),
    ("Hokkaido Consadole Sapporo", "北海道札幌冈萨多"),
    ("Giravanz Kitakyushu", "北九州向日葵"),
    ("Gainare Tottori", "鸟取飞翔"),
    ("Briobecca Urayasu", "浦安布里奥贝卡"),
    ("Veertien Mie", "三重维尔蒂恩"),
    ("Kriengri United", "桂里联"),
    ("YSCC Yokohama", "YSCC横滨"),
    # -- 韩国 --
    ("Gimpo FC", "金浦FC"),
    ("Cheonan City FC", "天安城"),
    ("Seoul E-Land FC", "首尔衣恋"),
    ("Hwaseong FC", "华城FC"),
    ("Gyeongnam FC", "庆南FC"),
    ("Seongnam FC", "城南FC"),
    ("Busan I Park", "釜山IPark"),
    ("Daegu FC", "大邱FC"),
    ("Ansan Greeners FC", "安山小绿人"),
    ("Jeonnam Dragons", "全南天龙"),
    ("Suwon FC", "水原FC"),
    ("Gimhae City FC", "金海市"),
    ("Yongin City FC", "龙仁市"),
    ("Chungnam Asan FC", "忠南牙山"),
    ("Incheon United", "仁川联"),
    ("Daejeon Hana Citizen", "大田韩亚市民"),
    ("Paju Citizen FC", "坡州市民"),
    ("Suwon Samsung Bluewings", "水原三星蓝翼"),
    ("Gangwon FC", "江原FC"),
    ("Bucheon FC 1995", "富川1995"),
    ("Jeonbuk Hyundai Motors", "全北现代"),
    ("Jeju SK", "济州SK"),
    ("Ulsan HD", "蔚山HD"),
    ("FC Anyang", "安阳FC"),
    ("Gwangju FC", "光州FC"),
    ("Pohang Steelers", "浦项铁人"),
    ("FC Seoul", "首尔FC"),
    ("Gimcheon Sangmu FC", "金泉尚武"),
    ("Daejeon Korail FC", "大田韩国铁道"),
    ("Mokpo City FC", "木浦市"),
    ("Changwon City FC", "昌原市"),
    ("Yangpyeong FC", "杨平FC"),
    ("Pocheon Citizen FC", "抱川市民"),
    # -- 智利 --
    ("Universidad de Chile", "智利大学"),
    ("Universidad Católica", "天主教大学"),
    ("Unión La Calera", "拉卡莱拉联合"),
    ("Deportes Concepción", "康塞普西翁体育"),
    ("Ñublense", "纽布伦塞"),
    ("Colo Colo", "科洛科洛"),
    ("Everton de Viña del Mar", "埃弗顿维尼亚德尔马"),
    ("Coquimbo Unido", "科金博联"),
    ("Audax Italiano", "奥达克斯意大利人"),
    ("O'Higgins", "奥希金斯"),
    ("Huachipato", "瓦奇巴托"),
    ("Deportes Limache", "利马切体育"),
    ("Deportes La Serena", "拉塞雷纳体育"),
    ("Universidad de Concepción", "康塞普西翁大学"),
    ("Cobresal", "科布雷萨尔"),
    ("Palestino", "巴勒斯坦人"),
    ("Santiago Wanderers", "圣地亚哥流浪者"),
    ("San Luis de Quillota", "圣路易斯基约塔"),
    ("Unión San Felipe", "圣费利佩联"),
    ("Deportes Iquique", "伊基克体育"),
    ("Cobreloa", "科布雷洛亚"),
    ("Magallanes", "麦哲伦"),
    ("Rangers de Talca", "塔尔卡流浪者"),
    ("Curicó Unido", "库里科联"),
    # -- 美国 MLS --
    ("New York City FC", "纽约城"),
    ("LA Galaxy", "洛杉矶银河"),
    ("San Jose Earthquakes", "圣何塞地震"),
    ("Real Salt Lake", "皇家盐湖城"),
    ("Seattle Sounders FC", "西雅图海湾人"),
    ("Colorado Rapids", "科罗拉多急流"),
    ("Sporting Kansas City", "堪萨斯城体育"),
    ("Chicago Fire", "芝加哥火焰"),
    ("FC Cincinnati", "辛辛那提FC"),
    ("DC United", "华盛顿联"),
    ("Charlotte FC", "夏洛特FC"),
    ("Miami FC", "迈阿密FC"),
    ("Inter Miami CF", "迈阿密国际"),
    ("Orlando City SC", "奥兰多城"),
    ("Portland Timbers", "波特兰伐木工"),
    ("Minnesota United", "明尼苏达联"),
    ("New England Revolution", "新英格兰革命"),
    ("Philadelphia Union", "费城联"),
    ("New York Red Bulls", "纽约红牛"),
    ("Atlanta United", "亚特兰大联"),
    ("Austin FC", "奥斯汀FC"),
    ("Houston Dynamo", "休斯顿迪纳摩"),
    ("Columbus Crew", "哥伦布机员"),
    ("Nashville SC", "纳什维尔SC"),
    ("San Diego FC", "圣迭戈FC"),
    ("Los Angeles FC", "洛杉矶FC"),
    ("New York Cosmos", "纽约宇宙"),
    ("Vancouver Whitecaps", "温哥华白帽"),
    ("Toronto FC", "多伦多FC"),
    ("CF Montréal", "蒙特利尔CF"),
    ("San Antonio FC", "圣安东尼奥FC"),
    ("Phoenix Rising FC", "凤凰重生"),
    ("Las Vegas Lights", "拉斯维加斯之光"),
    ("Orange County SC", "橙县SC"),
    ("Sacramento Republic FC", "萨克拉门托共和"),
    ("Detroit City FC", "底特律城"),
    ("Pittsburgh Riverhounds", "匹兹堡河犬"),
    ("Louisville City FC", "路易斯维尔城"),
    ("Birmingham Legion FC", "伯明翰军团"),
    ("Charleston Battery", "查尔斯顿电池"),
    ("Tampa Bay Rowdies", "坦帕湾粗汉"),
    ("Rhode Island FC", "罗德岛FC"),
    ("Hartford Athletic", "哈特福德竞技"),
    ("Indy Eleven", "印第安纳十一人"),
    ("El Paso Locomotive FC", "埃尔帕索机车"),
    ("Colorado Springs Switchbacks FC", "科罗拉多斯普林斯换向器"),
    ("New Mexico United", "新墨西哥联"),
    ("Monterey Bay FC", "蒙特雷湾FC"),
    ("Oakland Roots SC", "奥克兰根"),
    ("FC Tulsa", "塔尔萨"),
    ("Forward Madison FC", "麦迪逊前锋"),
    ("Union Omaha SC", "奥马哈联"),
    ("Richmond Kickers", "里士满踢球者"),
    ("Chattanooga Red Wolves SC", "查塔努加红狼"),
    ("North Carolina Courage", "北卡罗来纳勇气"),
    ("Portland Thorns FC", "波特兰荆棘"),
    ("Washington Spirit", "华盛顿精神"),
    ("Orlando Pride", "奥兰多荣耀"),
    ("Racing Louisville", "路易斯维尔竞技"),
    ("Angel City FC", "天使城FC"),
    ("NJ/NY Gotham FC", "哥谭FC"),
    ("Chicago Stars FC", "芝加哥星辰"),
    ("Bay FC", "海湾FC"),
    ("San Diego Wave FC", "圣迭戈波浪"),
    ("Seattle Reign FC", "西雅图君主"),
    ("Kansas City Current", "堪萨斯城潮流"),
    ("Houston Dash", "休斯顿达什"),
    ("Utah Royals FC", "犹他皇家"),
    ("Denver Summit FC", "丹佛顶峰"),
    ("Westchester SC", "韦斯特切斯特SC"),
    ("AV Alta FC", "AV阿尔塔FC"),
    ("SC Jacksonville", "杰克逊维尔SC"),
    ("Corpus Christi FC", "科珀斯克里斯蒂FC"),
    ("Sarasota Paradise", "萨拉索塔天堂"),
    ("One Knoxville SC", "诺克斯维尔SC"),
    ("Charlotte Independence", "夏洛特独立"),
    ("Lexington SC", "列克星敦SC"),
    ("Portland Hearts of Pine", "波特兰松心"),
    ("Loudoun United FC", "劳登联"),
    ("AC Boise", "博伊西AC"),
    ("Brooklyn FC", "布鲁克林FC"),
    ("Boston Legacy FC", "波士顿传承"),
    ("Spokane Velocity FC", "斯波坎极速"),
    ("FC Naples", "那不勒斯FC"),
    ("Greenville Triumph SC", "格林维尔胜利"),
    ("Fort Wayne FC", "韦恩堡FC"),
    ("Boston Legacy FC", "波士顿传承"),
    ("New York Cosmos", "纽约宇宙"),
    ("LA Galaxy II", "洛杉矶银河B队"),
    ("Columbus Crew 2", "哥伦布机员B队"),
    ("Philadelphia Union II", "费城联B队"),
    ("Chicago Fire II", "芝加哥火焰B队"),
    # -- 加拿大 --
    ("Vancouver FC", "温哥华FC"),
    ("Forge FC", "熔融FC"),
    ("Atlético Ottawa", "渥太华竞技"),
    ("Cavalry FC", "骑兵FC"),
    ("FC Supra Du Quebec", "魁北克超体"),
    ("York United FC", "约克联"),
    ("Pacific FC", "太平洋FC"),
    ("HFX Wanderers FC", "哈利法克斯流浪者"),
    ("Ottawa Fury FC", "渥太华狂怒"),
    ("FC Edmonton", "埃德蒙顿FC"),
    ("Valour FC", "勇士FC"),
    # -- 秘鲁 --
    ("Universitario", "大学体育"),
    ("Sport Huancayo", "万卡约体育"),
    ("Alianza Lima", "利马联盟"),
    ("Sporting Cristal", "水晶体育"),
    ("FC Cajamarca", "卡哈马卡FC"),
    ("Deportivo Garcilaso", "加尔西拉索体育"),
    ("Cusco FC", "库斯科FC"),
    ("Los Chankas CYC", "昌卡斯CYC"),
    ("Comerciantes Unidos", "联合商人"),
    ("Sport Boys", "男孩体育"),
    ("Alianza Atlético", "苏利亚纳联盟"),
    ("Club Atlético Grau", "格劳竞技"),
    ("Universidad Técnica de Cajamarca", "卡哈马卡技术大学"),
    ("Cienciano", "西恩夏诺"),
    ("Melgar", "梅尔加"),
    ("Alianza Atlético de Sullana", "苏利亚纳联盟竞技"),
    # -- 乌拉圭 --
    ("Liverpool UY", "利物浦(乌拉圭)"),
    ("Defensor Sporting", "防卫者体育"),
    ("Cerro", "塞罗"),
    ("Progreso", "进步"),
    ("Montevideo City Torque", "蒙得维的亚城扭矩"),
    ("Montevideo Wanderers", "蒙得维的亚流浪者"),
    ("Boston River", "波士顿河"),
    ("Deportivo Maldonado", "马尔多纳多体育"),
    ("Juventud de Las Piedras", "拉斯彼德拉斯青年"),
    ("Danubio", "达努比奥"),
    ("Racing de Montevideo", "蒙得维的亚竞技"),
    ("Cerro Largo", "塞罗拉尔戈"),
    ("Nacional", "民族(乌拉圭)"),
    ("Peñarol", "佩纳罗尔"),
    ("Albion FC", "阿尔比恩FC"),
    ("Central Español", "中央西班牙人"),
    ("Recoleta FC", "雷科莱塔FC"),
    # -- 阿根廷 --
    ("Barracas Central", "巴拉卡斯中央"),
    ("Instituto De Córdoba", "科尔多瓦学院"),
    ("Gimnasia Jujuy", "胡胡伊体操"),
    ("Boca Juniors", "博卡青年"),
    ("Tigre", "老虎"),
    ("San Lorenzo", "圣洛伦索"),
    ("Lanús", "拉努斯"),
    ("Racing Club", "竞技"),
    ("River Plate", "河床"),
    ("Estudiantes de La Plata", "拉普拉塔大学生"),
    ("Belgrano", "贝尔格拉诺"),
    ("Vélez Sarsfield", "萨斯菲尔德"),
    ("Independiente Rivadavia", "独立里瓦达维亚"),
    ("Banfield", "班菲尔德"),
    ("Aldosivi", "阿尔多西维"),
    ("Gimnasia y Esgrima", "拉普拉塔体操"),
    ("Atlético Tucumán", "图库曼竞技"),
    ("Newell's Old Boys", "纽维尔老男孩"),
    ("Sarmiento", "萨米恩托"),
    ("Huracán", "飓风"),
    ("Defensa y Justicia", "防卫与正义"),
    ("Deportivo Riestra", "列斯特拉体育"),
    ("Estudiantes de Río Cuarto", "里奥夸尔托大学生"),
    ("Gimnasia y Esgrima Mendoza", "门多萨体操"),
    ("Deportivo Morón", "莫龙体育"),
    ("Acassuso", "阿卡苏索"),
    ("CA Independiente", "独立"),
    ("Rosario Central", "罗萨里奥中央"),
    ("Talleres", "塔莱雷斯"),
    ("Platense", "普拉滕斯"),
    ("Central Córdoba", "科尔多瓦中央"),
    ("Unión de Santa Fe", "圣菲联"),
    ("Colón", "科隆"),
    ("Godoy Cruz", "戈多伊克鲁斯"),
    ("Argentinos Juniors", "阿根廷青年"),
    ("Chacarita Juniors", "查卡里塔青年"),
    ("Quilmes", "基尔梅斯"),
    ("Almagro", "阿尔马格罗"),
    ("Atlanta", "亚特兰大"),
    ("San Martín de Tucumán", "圣马丁图库曼"),
    ("San Martín de San Juan", "圣马丁圣胡安"),
    ("Deportivo Maipú", "迈普体育"),
    ("Nueva Chicago", "新芝加哥"),
    ("Brown de Adrogué", "阿德罗格布朗"),
    ("Almirante Brown", "布朗海军上将"),
    ("Temperley", "坦珀利"),
    ("Ferro Carril Oeste", "西部铁路"),
    ("All Boys", "全男孩"),
    ("Estudiantes Caseros", "卡塞罗斯大学生"),
    ("Club Atlético Mitre", "米特雷"),
    ("Crucero del Norte", "北方巡游者"),
    # -- 墨西哥 --
    ("CD Toluca", "托卢卡"),
    ("Pumas UNAM", "国立自治大学"),
    ("Club América", "美洲"),
    ("Tigres UANL", "老虎大学"),
    ("CF Pachuca", "帕丘卡"),
    ("Atlas FC", "阿特拉斯"),
    ("Santos Laguna", "桑托斯拉古纳"),
    ("Club Necaxa", "内卡萨"),
    ("Club Tijuana", "蒂华纳"),
    ("Mazatlán FC", "马萨特兰"),
    ("Atlético San Luis", "圣路易斯竞技"),
    ("Club León", "莱昂"),
    ("CF Monterrey", "蒙特雷"),
    ("Querétaro FC", "克雷塔罗"),
    ("CD Guadalajara", "瓜达拉哈拉"),
    ("FC Juárez", "华雷斯"),
    ("Club Puebla", "普埃布拉"),
    ("Cruz Azul", "蓝十字"),
    ("Monarcas Morelia", "莫雷利亚君主"),
    ("Mineros de Zacatecas", "萨卡特卡斯矿工"),
    ("Tepatitlán FC", "特帕蒂特兰"),
    ("Dorados de Sinaloa", "锡那罗亚多拉多斯"),
    ("Atlante FC", "亚特兰特"),
    ("Venados FC", "鹿FC"),
    ("Alebrijes de Oaxaca", "瓦哈卡"),
    ("Cimarrones de Sonora", "索诺拉海员"),
    ("Correcaminos UAT", "UAT快车"),
    ("CD Tapatío", "塔帕提奥"),
    # -- 哥伦比亚 --
    ("Atlético Nacional", "国民竞技"),
    ("Junior Barranquilla", "巴兰基亚青年"),
    ("Millonarios", "百万富翁"),
    ("Deportivo Pasto", "帕斯托体育"),
    ("Once Caldas", "卡尔达斯"),
    ("Independiente Santa Fe", "圣菲独立"),
    ("Deportes Tolima", "托利马体育"),
    ("Deportivo Cali", "卡利体育"),
    ("Alianza Valledupar FC", "巴耶杜帕尔联盟"),
    ("Independiente Medellín", "麦德林独立"),
    ("Fortaleza CEIF", "福塔莱萨CEIF"),
    ("Boyacá Chicó FC", "博亚卡奇科"),
    ("Cúcuta Deportivo", "库库塔体育"),
    ("Deportivo Pereira", "佩雷拉体育"),
    ("Rionegro Águilas", "里奥内格罗金鹰"),
    ("Llaneros FC", "拉内罗斯"),
    ("Internacional de Bogotá", "波哥大国际"),
    ("La Equidad", "公平"),
    ("Envigado FC", "恩维加多"),
    ("Jaguares de Córdoba", "科尔多瓦美洲虎"),
    ("Atlético Bucaramanga", "布卡拉曼加竞技"),
    ("Real Cartagena", "卡塔赫纳皇家"),
    ("Orsomarso SC", "奥索马索"),
    ("Real Santander", "桑坦德皇家"),
    ("Barranquilla FC", "巴兰基亚FC"),
    ("Boca Juniors de Cali", "博卡青年卡利"),
    ("Leones FC", "雄狮FC"),
    ("Valledupar FC", "巴耶杜帕尔FC"),
    ("Atlético Cali FC", "卡利竞技"),
    # -- 巴拉圭 --
    ("Cerro Porteño", "波特诺山丘"),
    ("Nacional Asunción", "亚松森国民"),
    ("Sportivo Ameliano", "阿梅利亚诺体育"),
    ("Sportivo Luqueño", "卢克尼奥体育"),
    ("Guaraní", "瓜拉尼"),
    ("Sportivo Trinidense", "特立尼登斯体育"),
    ("Rubio Ñu", "鲁比奥纽"),
    ("CS 2 de Mayo", "5月2日"),
    ("Olimpia", "奥林匹亚"),
    ("Sol de América", "美洲太阳"),
    ("Libertad Asunción", "亚松森自由"),
    ("General Caballero JLM", "卡瓦列罗将军"),
    ("Tacuary", "塔夸里"),
    ("Guaireña FC", "瓜伊雷尼亚"),
    # -- 玻利维亚 --
    ("Bolívar", "玻利瓦尔"),
    ("Club Always Ready", "时刻准备着"),
    ("The Strongest", "最强者"),
    ("Club Aurora", "奥罗拉"),
    ("Nacional Potosí", "波托西国民"),
    ("San Antonio Bulo-Bulo", "圣安东尼奥布鲁布鲁"),
    ("Guabirá", "瓜比拉"),
    ("Real Tomayapo", "皇家托马亚波"),
    ("GV San José", "GV圣何塞"),
    ("Universitario de Vinto", "文托大学"),
    ("Real Potosí", "皇家波托西"),
    ("CDT Real Oruro", "皇家奥鲁罗"),
    ("Academia del Balompié Boliviano", "玻利维亚足球队"),
    ("Blooming", "布卢明"),
    ("Oriente Petrolero", "东方石油"),
    ("Royal Pari FC", "皇家帕里"),
    ("Independiente Petrolero", "石油独立"),
    ("Municipal Vinto", "文托市政"),
    # -- 厄瓜多尔 --
    ("Emelec", "埃梅莱克"),
    ("Guayaquil City", "瓜亚基尔城"),
    ("Deportivo Cuenca", "昆卡体育"),
    ("Técnico Universitario", "技术大学"),
    ("Mushuc Runa", "穆舒克鲁纳"),
    ("Delfín", "德尔芬"),
    ("Manta FC", "曼塔FC"),
    ("Barcelona SC", "巴塞罗那SC"),
    ("Aucas", "奥卡斯"),
    ("Independiente del Valle", "山谷独立"),
    ("LDU", "基多大学"),
    ("Orense SC", "奥伦塞SC"),
    ("Universidad Católica del Ecuador", "厄瓜多尔天主教大学"),
    ("Libertad", "自由"),
    ("El Nacional", "民族"),
    ("Cumbayá FC", "昆巴亚"),
    ("Imbabura SC", "因巴布拉"),
    ("Macará", "马卡拉"),
    ("Técnico Universitario", "技术大学"),
    ("Vargas Torres", "巴尔加斯托雷斯"),
    ("CDS Santa Rita", "圣丽塔"),
    ("9 de Octubre", "10月9日"),
    # -- 委内瑞拉 --
    ("Caracas F.C.", "加拉加斯FC"),
    ("Deportivo La Guaira", "拉瓜伊拉体育"),
    ("Carabobo", "卡拉沃沃"),
    ("Portuguesa", "葡萄牙人"),
    ("Mineros de Guayana", "圭亚那矿工"),
    ("Zulia", "苏利亚"),
    ("Estudiantes de Mérida", "梅里达大学生"),
    ("Trujillanos", "特鲁希利亚诺斯"),
    ("Metropolitanos", "大都会"),
    ("Monagas", "莫纳加斯"),
    ("Angostura", "安戈斯图拉"),
    ("Academia Puerto Cabello", "卡贝略港学院"),
    ("Deportivo Táchira", "塔奇拉体育"),
    ("Rayo Zuliano", "苏利亚闪电"),
    ("Hermanos Colmenares", "科梅纳雷斯兄弟"),
    ("Lala FC", "拉拉FC"),
    ("Ureña SC", "乌雷尼亚"),
    # -- 摩洛哥 --
    ("RS Berkane", "贝尔卡内"),
    ("Wydad Casablanca", "卡萨布兰卡维达德"),
    ("AS FAR Rabat", "拉巴特皇家武装力量"),
    ("Ittihad Tanger", "丹吉尔联"),
    ("Hassania d'Agadir", "阿加迪尔哈萨尼亚"),
    ("Raja Club Athletic", "拉贾卡萨布兰卡"),
    ("Fath Union Sport", "FUS拉巴特"),
    ("Olympic Safi", "萨菲奥林匹克"),
    ("CODM Meknès", "梅克内斯COD"),
    ("Difaâ Hassani El-Jadidi", "杰迪代迪法"),
    ("Moghreb Tétouan", "得土安马格里布"),
    ("Union Touarga Sport", "图尔加联合"),
    ("Kawkab Athletic Club Marrakech", "卡乌卡布马拉喀什"),
    ("Renaissance Zemamra", "泽马姆拉复兴"),
    ("MAS de Fès", "非斯MAS"),
    ("Union Sportive Yacoub El Mansour", "雅各布曼苏尔联合"),
    ("Olympique Dcheira", "德切拉奥林匹克"),
    ("Chabab Benguerir", "本格里尔青年"),
    ("JS Soualem", "苏阿莱姆青年"),
    ("Mouloudia Oujda", "乌季达穆卢迪亚"),
    ("Olympique Khouribga", "胡里布盖奥林匹克"),
    ("Chabab Mohammédia", "穆罕默迪耶"),
    ("IR Tanger", "丹吉尔IR"),
    # -- 阿尔及利亚 --
    ("MC Oran", "奥兰MC"),
    ("JS Saoura", "萨乌拉青年"),
    ("JS Kabylie", "卡比利青年"),
    ("MC Alger", "阿尔及尔MC"),
    ("USM Khenchela", "汉舍莱USM"),
    ("ES Mostaganem", "莫斯塔加内姆ES"),
    ("Paradou AC", "帕拉杜AC"),
    ("USM Alger", "阿尔及尔USM"),
    ("CR Belouizdad", "贝鲁兹达德CR"),
    ("CS Constantine", "君士坦丁CS"),
    ("ES Sétif", "塞提夫ES"),
    ("ASO Chlef", "谢里夫ASO"),
    ("MC El Bayadh", "巴亚兹MC"),
    ("ES Ben Aknoun", "本阿克努ES"),
    ("Olympique Akbou", "阿克布奥林匹克"),
    ("MB Rouissat", "鲁伊萨特MB"),
    ("NC Magra", "马格拉"),
    ("HB Chelghoum Laïd", "谢勒古姆莱德"),
    ("US Biskra", "比斯克拉"),
    ("RC Arbaâ", "阿尔巴"),
    # -- 埃及 --
    ("Al Ahly FC", "开罗国民"),
    ("Pyramids FC", "金字塔"),
    ("Zamalek SC", "扎马雷克"),
    ("Al-Masry", "马斯里"),
    ("Ceramica Cleopatra", "克娄巴特拉陶瓷"),
    ("Smouha", "斯穆哈"),
    ("ENPPI", "恩皮"),
    ("Ghazl El Mahalla", "马哈拉工人"),
    ("National Bank of Egypt", "埃及国民银行"),
    ("Al-Mokawloon", "莫卡伍伦"),
    ("ZED FC", "ZEDFC"),
    ("Ismaily", "伊斯梅利"),
    ("Petrojet", "石油喷射"),
    ("Tala'ea El-Gaish", "塔拉埃盖什"),
    ("Pharco FC", "法尔科"),
    ("El Gouna FC", "古纳"),
    ("Haras El Hodood", "哈拉斯埃尔霍杜德"),
    ("El Dakhleya", "达赫莱亚"),
    ("Future FC", "未来FC"),
    # -- 南非 --
    ("Cape Town City FC", "开普敦城"),
    ("Magesi FC", "马格西"),
    ("Mamelodi Sundowns", "马梅洛迪日落"),
    ("Orlando Pirates", "奥兰多海盗"),
    ("Kaizer Chiefs", "凯撒酋长"),
    ("Stellenbosch", "斯泰伦博斯"),
    ("Richards Bay FC", "理查兹湾"),
    ("Chippa United", "奇帕联"),
    ("Polokwane City", "波罗瓜尼城"),
    ("AmaZulu FC", "阿马祖鲁"),
    ("TS Galaxy", "TS银河"),
    ("Sekhukhune United", "塞库库内联"),
    ("SuperSport United", "超体联"),
    ("Royal AM", "皇家AM"),
    ("Moroka Swallows", "莫罗卡燕子"),
    ("Baroka FC", "巴罗卡"),
    ("Golden Arrows", "金箭"),
    # -- 中国 --
    ("Wuhan Three Towns", "武汉三镇"),
    ("Tianjin Jinmen Tiger", "天津津门虎"),
    ("Shenzhen Peng City", "深圳新鹏城"),
    ("Chongqing Tonglianglong FC", "重庆铜梁龙"),
    ("Chengdu Rongcheng", "成都蓉城"),
    ("Henan FC Jiuzu Dukang", "河南酒祖杜康"),
    ("Qingdao West Coast", "青岛西海岸"),
    ("Shanghai Shenhua", "上海申花"),
    ("Zhejiang", "浙江"),
    ("Shandong Taishan", "山东泰山"),
    ("Yunnan Yukun", "云南玉昆"),
    ("Qingdao Hainiu", "青岛海牛"),
    ("Liaoning Tieren FC", "辽宁铁人"),
    ("Shenzhen Peng City", "深圳新鹏城"),
    ("Shanghai Port", "上海海港"),
    ("Beijing Guoan", "北京国安"),
    ("Changchun Yatai", "长春亚泰"),
    ("Meizhou Hakka", "梅州客家"),
    ("Nantong Zhiyun", "南通支云"),
    ("Cangzhou Mighty Lions", "沧州雄狮"),
    # -- 越南 --
    ("PVF-Công An Nhân Dân", "PVF人民公安"),
    ("SHB Đà Nẵng", "SHB岘港"),
    ("Hải Phòng", "海防"),
    ("Thể Công - Viettel", "体工越电信"),
    ("Sông Lam Nghệ An", "义安蓝江"),
    ("Phù Đổng Ninh Bình", "扶董宁平"),
    ("Hà Nội", "河内"),
    ("Becamex Bình Dương", "贝卡麦斯平阳"),
    ("Công An Hà Nội", "河内公安"),
    ("Nam Định", "南定"),
    ("Hoàng Anh Gia Lai", "嘉莱黄英"),
    ("Hồng Lĩnh Hà Tĩnh", "红林河静"),
    ("Đông Á Thanh Hóa", "东亚清化"),
    ("Hồ Chí Minh City", "胡志明市"),
    ("Bà Rịa Vũng Tàu", "巴地头顿"),
    ("Khánh Hòa", "庆和"),
    ("Cần Thơ", "芹苴"),
    ("Huế", "顺化"),
    # -- 泰国 --
    ("Buriram United", "武里南联"),
    ("BG Pathum United", "巴吞联"),
    ("Muang Thong United", "蒙通联"),
    ("Port FC", "港口FC"),
    ("True Bangkok United", "真曼谷联"),
    ("Chonburi FC", "春武里"),
    ("Chiangrai United", "清莱联"),
    ("Rayong FC", "罗勇"),
    ("Ayutthaya United", "大城联"),
    ("Kanchanaburi Power FC", "北碧力量"),
    ("Sukhothai", "素可泰"),
    ("Lamphun Warrior", "南奔勇士"),
    ("Ratchaburi", "拉差布里"),
    ("PT Prachuap FC", "巴蜀基里"),
    ("Nakhon Ratchasima Mazda FC", "那空拉查斯马"),
    ("Uthai Thani FC", "乌泰他尼"),
    ("Trat FC", "达叻"),
    ("Nongbua Pitchaya", "农布阿比查亚"),
    ("Khon Kaen United", "孔敬联"),
    ("Police Tero FC", "特罗警察"),
    ("Samut Prakan City", "北榄城"),
    # -- 印尼 --
    ("PSM Makassar", "PSM望加锡"),
    ("PSIM Yogyakarta", "PSIM日惹"),
    ("Persijap Jepara", "帕萨甲帕拉"),
    ("Malut United FC", "马鲁特联"),
    ("Persis Solo", "佩西斯梭罗"),
    ("Persik Kediri", "佩西克谏义里"),
    ("Bali United FC", "巴厘联"),
    ("PSBS Biak", "PSBS比亚克"),
    ("Semen Padang FC", "塞门巴东"),
    ("Arema FC", "阿雷马"),
    ("Persebaya Surabaya", "泗水佩塞巴亚"),
    ("Persib Bandung", "万隆佩西布"),
    ("Persija Jakarta", "雅加达佩西加"),
    ("PSM Makassar", "望加锡"),
    ("Borneo FC", "婆罗洲FC"),
    ("Persita Tangerang", "唐格朗佩西塔"),
    ("Barito Putera", "巴里托普特拉"),
    ("RANS Nusantara FC", "RANS努桑塔拉"),
    ("Dewa United FC", "德瓦联"),
    ("PSS Sleman", "PSS斯莱曼"),
    ("Persikabo 1973", "佩西卡博1973"),
    ("Persewangi Banyuwangi", "外南梦佩塞万吉"),
    # -- 马来西亚 --
    ("Kuching City", "古晋城"),
    ("Selangor Football Club", "雪兰莪"),
    ("Penang", "槟城"),
    ("Sabah FC", "沙巴"),
    ("Johor Darul Ta'zim", "柔佛达鲁塔克欣"),
    ("Kuala Lumpur City FC", "吉隆坡城"),
    ("Kelantan Darul Naim", "吉兰丹"),
    ("Melaka FC", "马六甲"),
    ("PDRM FC", "马来西亚警察"),
    ("Negeri Sembilan", "森美兰"),
    ("Brunei DPMM FC", "文莱DPMM"),
    ("Terengganu", "登嘉楼"),
    ("Perak FC", "霹雳"),
    ("Kedah FC", "吉打"),
    ("Pahang FC", "彭亨"),
    ("Sri Pahang FC", "彭亨"),
    ("Kelantan FC", "吉兰丹FC"),
    ("Petaling Jaya City FC", "八打灵再也城"),
    ("UiTM FC", "玛拉工艺大学"),
    ("Sarawak United FC", "砂拉越联"),
    # -- 新加坡 --
    ("Albirex Niigata (S)", "新潟天鹅新加坡"),
    ("Lion City Sailors", "狮城水手"),
    ("Tampines Rovers", "淡滨尼流浪者"),
    ("Geylang International", "芽笼国际"),
    ("Young Lions", "幼狮"),
    ("Hougang United", "后港联"),
    ("Balestier Khalsa", "巴莱斯提耶卡沙"),
    ("DPMM FC", "文莱DPMM"),
    # -- 印度 --
    ("NorthEast United", "东北联"),
    ("Kerala Blasters", "喀拉拉爆破手"),
    ("Mohun Bagan Super Giant", "莫亨巴根"),
    ("Hyderabad FC", "海得拉巴"),
    ("Odisha FC", "奥迪沙"),
    ("Chennaiyin FC", "金奈FC"),
    ("Mohammedan SC", "穆罕默德"),
    ("East Bengal FC", "东孟加拉"),
    ("Jamshedpur FC", "贾姆谢德布尔"),
    ("FC Goa", "果阿"),
    ("Mumbai City FC", "孟买城"),
    ("Bengaluru FC", "班加罗尔"),
    ("ATK Mohun Bagan", "ATK莫亨巴根"),
    ("SC East Bengal", "SC东孟加拉"),
    ("Punjab FC", "旁遮普FC"),
    # -- 澳大利亚 --
    ("Newcastle Jets", "纽卡斯尔喷气机"),
    ("Adelaide United", "阿德莱德联"),
    ("Sydney FC", "悉尼FC"),
    ("Melbourne Victory", "墨尔本胜利"),
    ("Perth Glory", "珀斯光荣"),
    ("Melbourne City", "墨尔本城"),
    ("Western Sydney Wanderers", "西悉尼流浪者"),
    ("Macarthur FC", "麦克阿瑟FC"),
    ("Central Coast Mariners", "中央海岸水手"),
    ("Brisbane Roar", "布里斯班狮吼"),
    ("Western United", "西部联"),
    ("Wellington Phoenix", "惠灵顿凤凰"),
    # -- 法乙 --
    ("Red Star FC", "红星"),
    ("USL Dunkerque", "敦刻尔克"),
    ("US Boulogne Côte-d'Opale", "布洛涅"),
    ("Le Mans", "勒芒"),
    ("Rodez AF", "罗德兹"),
    ("Amiens SC", "亚眠"),
    ("Guingamp", "甘冈"),
    ("Pau FC", "波城"),
    ("Troyes", "特鲁瓦"),
    ("Annecy FC", "昂纳西"),
    ("Nancy", "南锡"),
    ("Bastia", "巴斯蒂亚"),
    ("Clermont Foot", "克莱蒙"),
    ("Grenoble Foot 38", "格勒诺布尔"),
    ("FC Rouen", "鲁昂"),
    ("Stade Lavallois", "拉瓦勒"),
    ("CS Sedan Ardennes", "色当"),
    ("FC Versailles 78", "凡尔赛78"),
    ("Dijon FCO", "第戎"),
    ("Quevilly-Rouen", "克维伊鲁昂"),
    ("Bordeaux", "波尔多"),
    ("Saint-Étienne", "圣埃蒂安"),
    ("Valenciennes FC", "瓦朗谢讷"),
    ("Nîmes Olympique", "尼姆"),
    ("Sochaux", "索肖"),
    ("LB Châteauroux", "沙托鲁"),
    ("Orléans", "奥尔良"),
    ("Le Puy Foot", "勒皮"),
    ("GOAL FC", "GOALFC"),
    # -- 法国其他 --
    ("Paris Saint-Germain", "巴黎圣日耳曼"),
    ("Olympique Lyonnais", "里昂"),
    ("Paris FC", "巴黎FC"),
    ("Stade Brestois", "布雷斯特"),
    ("Olympique de Marseille", "马赛"),
    ("Lille", "里尔"),
    ("RC Strasbourg", "斯特拉斯堡"),
    ("Lorient", "洛里昂"),
    ("AS Monaco", "摩纳哥"),
    ("Auxerre", "欧塞尔"),
    ("Angers", "昂热"),
    ("Metz", "梅斯"),
    ("Toulouse", "图卢兹"),
    ("Stade Rennais", "雷恩"),
    ("Le Havre", "勒阿弗尔"),
    ("Nantes", "南特"),
    ("Montpellier", "蒙彼利埃"),
    ("Nice", "尼斯"),
    ("Stade de Reims", "兰斯"),
    # -- 英冠/英甲/英乙 --
    ("West Ham United", "西汉姆联"),
    ("Tottenham Hotspur", "托特纳姆热刺"),
    ("Sunderland", "桑德兰"),
    ("Fulham", "富勒姆"),
    ("Nottingham Forest", "诺丁汉森林"),
    ("Liverpool", "利物浦"),
    ("Manchester City", "曼城"),
    ("Burnley", "伯恩利"),
    ("Brighton & Hove Albion", "布莱顿"),
    ("Chelsea", "切尔西"),
    ("Bournemouth", "伯恩茅斯"),
    ("Arsenal", "阿森纳"),
    ("Crystal Palace", "水晶宫"),
    ("Newcastle United", "纽卡斯尔联"),
    ("Wolverhampton", "狼队"),
    ("Everton", "埃弗顿"),
    ("Leeds United", "利兹联"),
    ("Brentford", "布伦特福德"),
    ("Manchester United", "曼联"),
    ("Southampton", "南安普顿"),
    ("Aston Villa", "阿斯顿维拉"),
    ("Leicester City", "莱斯特城"),
    ("Middlesbrough", "米德尔斯堡"),
    ("Blackburn Rovers", "布莱克本"),
    ("Derby County", "德比郡"),
    ("Bristol City", "布里斯托尔城"),
    ("Ipswich Town", "伊普斯维奇"),
    ("Preston North End", "普雷斯顿"),
    ("Watford", "沃特福德"),
    ("Swansea City", "斯旺西"),
    ("Portsmouth", "朴茨茅斯"),
    ("Sheffield Wednesday", "谢周三"),
    ("Wrexham", "雷克瑟姆"),
    ("Coventry City", "考文垂"),
    ("Huddersfield Town", "哈德斯菲尔德"),
    ("Blackpool", "布莱克浦"),
    ("Burton Albion", "伯顿"),
    ("Cardiff City", "加的夫城"),
    ("Lincoln City", "林肯城"),
    ("Luton Town", "卢顿"),
    ("Plymouth Argyle", "普利茅斯"),
    ("Bristol Rovers", "布里斯托流浪者"),
    ("Colchester United", "科尔切斯特联"),
    ("Wigan Athletic", "维冈"),
    ("Walsall", "沃尔索尔"),
    ("Shrewsbury Town", "什鲁斯伯里"),
    ("Accrington Stanley", "阿克灵顿"),
    ("Newport County", "纽波特郡"),
    ("Barnet", "巴尼特"),
    ("Rotherham United", "罗瑟汉姆"),
    ("Cambridge United", "剑桥联"),
    ("Norwich City", "诺维奇"),
    ("Birmingham City", "伯明翰"),
    ("Oxford United", "牛津联"),
    ("Queens Park Rangers", "女王公园巡游者"),
    ("Sheffield United", "谢菲联"),
    ("Stoke City", "斯托克城"),
    ("Millwall", "米尔沃尔"),
    ("Stockport County", "斯托克波特"),
    ("Bolton Wanderers", "博尔顿"),
    ("Barnsley", "巴恩斯利"),
    ("Exeter City", "埃克塞特城"),
    ("Leyton Orient", "莱顿东方"),
    ("Mansfield Town", "曼斯菲尔德"),
    ("Northampton Town", "北安普顿"),
    ("Peterborough United", "彼得堡联"),
    ("Port Vale", "韦尔港"),
    ("Reading", "雷丁"),
    ("Wycombe Wanderers", "威科姆"),
    ("Swindon Town", "斯温登"),
    ("Barrow AFC", "巴罗"),
    ("Crawley Town", "克劳利"),
    ("Fleetwood Town", "弗利特伍德"),
    ("Cheltenham Town", "切尔滕纳姆"),
    ("Crewe Alexandra", "克鲁"),
    ("Gillingham", "吉灵汉姆"),
    ("Oldham Athletic", "奥尔德姆"),
    ("AFC Wimbledon", "温布尔登"),
    ("Bromley", "布罗姆利"),
    ("Tranmere Rovers", "特兰米尔"),
    ("Harrogate Town", "哈罗盖特"),
    ("Salford City", "索尔福德"),
    ("Bradford City", "布拉德福德"),
    ("Chesterfield", "切斯特菲尔德"),
    ("Grimsby Town", "格里姆斯比"),
    ("Boreham Wood", "博勒姆伍德"),
    ("Morecambe", "莫克姆"),
    ("Braintree Town", "布伦特里"),
    ("York City", "约克城"),
    ("Eastleigh", "伊斯特利"),
    ("Gateshead", "盖茨黑德"),
    ("Solihull Moors", "索利赫尔"),
    ("Sutton United", "萨顿联"),
    ("Wealdstone", "韦尔德斯通"),
    ("Truro City", "特鲁罗城"),
    ("FC Halifax Town", "哈利法克斯"),
    ("Aldershot Town", "奥尔德肖特"),
    ("Altrincham", "奥特林查姆"),
    ("Boston United", "波士顿联"),
    ("Forest Green Rovers", "绿色森林"),
    ("Southend United", "绍森德联"),
    ("Tamworth", "塔姆沃思"),
    ("Woking", "沃金"),
    ("Yeovil Town", "约维尔"),
    ("Doncaster Rovers", "唐卡斯特"),
    ("Milton Keynes Dons", "米尔顿凯恩斯"),
    ("Charlton Athletic", "查尔顿"),
    ("West Bromwich Albion", "西布朗"),
    ("Notts County", "诺茨郡"),
    ("Hartlepool United", "哈特尔普尔"),
    ("Stevenage", "斯蒂文尼奇"),
    ("Scunthorpe United", "斯肯索普"),
    ("Rochdale", "罗奇代尔"),
    # -- 苏格兰 --
    ("St. Mirren", "圣米伦"),
    ("Hibernian", "希伯尼安"),
    ("Motherwell", "马瑟韦尔"),
    ("Rangers", "流浪者"),
    ("Heart of Midlothian", "哈茨"),
    ("Dundee FC", "邓迪FC"),
    ("Aberdeen", "阿伯丁"),
    ("Kilmarnock", "基尔马诺克"),
    ("Dundee United", "邓迪联"),
    ("Dunfermline Athletic", "邓弗姆林"),
    ("Ross County", "罗斯郡"),
    ("St. Johnstone", "圣约翰斯通"),
    ("Queen's Park FC", "女王公园"),
    ("Ayr United", "艾尔联"),
    ("Greenock Morton", "格里斯诺克莫顿"),
    ("Raith Rovers", "雷斯流浪者"),
    ("Livingston", "利文斯顿"),
    ("Falkirk FC", "福尔柯克"),
    ("Alloa Athletic", "阿洛厄"),
    ("Stenhousemuir", "斯坦豪斯穆尔"),
    ("Arbroath", "阿布罗斯"),
    ("Airdrieonians", "艾尔德里人"),
    ("Queen of The South", "南部女王"),
    # -- 西甲/西乙 --
    ("Almería", "阿尔梅里亚"),
    ("Leganés", "莱加内斯"),
    ("Córdoba", "科尔多瓦"),
    ("Racing de Santander", "桑坦德竞技"),
    ("Deportivo La Coruña", "拉科鲁尼亚"),
    ("Real Zaragoza", "皇家萨拉戈萨"),
    ("Burgos Club de Fútbol", "布尔戈斯"),
    ("Málaga", "马拉加"),
    ("Athletic Club", "毕尔巴鄂竞技"),
    ("Las Palmas", "拉斯帕尔马斯"),
    ("CD Castellón", "卡斯特利翁"),
    ("Sporting Gijón", "希洪竞技"),
    ("Eibar", "埃瓦尔"),
    ("Cultural Leonesa", "莱昂内萨"),
    ("Mirandés", "米兰德斯"),
    ("Real Valladolid", "巴利亚多利德"),
    ("Cádiz", "加的斯"),
    ("Huesca", "韦斯卡"),
    ("Girona FC", "赫罗纳"),
    ("Valencia", "巴伦西亚"),
    ("Real Madrid", "皇家马德里"),
    ("Mallorca", "马略卡"),
    ("Getafe", "赫塔费"),
    ("Espanyol", "西班牙人"),
    ("Celta Vigo", "塞尔塔"),
    ("Real Betis", "皇家贝蒂斯"),
    ("Deportivo Alavés", "阿拉维斯"),
    ("Sevilla", "塞维利亚"),
    ("Osasuna", "奥萨苏纳"),
    ("Real Oviedo", "皇家奥维耶多"),
    ("Real Sociedad", "皇家社会"),
    ("Rayo Vallecano", "巴列卡诺"),
    ("Levante UD", "莱万特"),
    ("Elche", "埃尔切"),
    ("Atlético Madrid", "马德里竞技"),
    ("Villarreal", "比利亚雷亚尔"),
    ("Granada", "格拉纳达"),
    ("AD Ceuta", "休达"),
    ("Real Sociedad B", "皇家社会B"),
    ("Albacete Balompié", "阿尔瓦塞特"),
    ("FC Andorra", "安道尔FC"),
    ("Tenerife", "特内里费"),
    ("Cartagena", "卡塔赫纳"),
    ("UD Ibiza", "伊维萨"),
    ("FC Cartagena", "卡塔赫纳"),
    ("Lugo", "卢戈"),
    ("Ponferradina", "蓬费拉迪纳"),
    ("Fuenlabrada", "富恩拉夫拉达"),
    ("UD Logroñés", "洛格罗涅斯"),
    ("Sabadell", "萨瓦德尔"),
    # -- 意甲/意乙 --
    ("Monza", "蒙扎"),
    ("Torino", "都灵"),
    ("Milan", "AC米兰"),
    ("Cremonese", "克雷莫纳"),
    ("Lecce", "莱切"),
    ("Hellas Verona", "维罗纳"),
    ("Catanzaro", "卡坦扎罗"),
    ("Napoli", "那不勒斯"),
    ("Parma", "帕尔马"),
    ("Inter", "国际米兰"),
    ("Juventus", "尤文图斯"),
    ("Como", "科莫"),
    ("Genoa", "热那亚"),
    ("Pisa", "比萨"),
    ("Roma", "罗马"),
    ("Atalanta", "亚特兰大"),
    ("Udinese", "乌迪内斯"),
    ("Cagliari", "卡利亚里"),
    ("Sassuolo", "萨索洛"),
    ("Palermo", "巴勒莫"),
    ("Bari", "巴里"),
    ("Venezia", "威尼斯"),
    ("Reggiana", "雷吉亚纳"),
    ("Frosinone", "弗罗西诺内"),
    ("Pescara", "佩斯卡拉"),
    ("Cesena", "切塞纳"),
    ("Virtus Entella", "恩特拉"),
    ("Avellino", "阿韦利诺"),
    ("Spezia", "斯佩齐亚"),
    ("Sampdoria", "桑普多利亚"),
    ("Modena", "摩德纳"),
    ("Empoli", "恩波利"),
    ("Mantova", "曼托瓦"),
    ("Carrarese", "卡拉雷塞"),
    ("Juve Stabia", "斯塔比亚"),
    ("Padova", "帕多瓦"),
    ("Cosenza", "科森扎"),
    ("Cittadella", "奇塔代拉"),
    (" Südtirol", "南蒂罗尔"),
    ("Brescia", "布雷西亚"),
    ("Ascoli", "阿斯科利"),
    ("Salernitana", "萨勒尼塔纳"),
    ("Perugia", "佩鲁贾"),
    ("Vicenza", "维琴察"),
    ("LR Vicenza", "维琴察"),
    ("Feralpisalò", "费拉尔皮萨洛"),
    ("Lecco", "莱科"),
    # -- 德甲/德乙 --
    ("SpVgg Greuther Fürth", "菲尔特"),
    ("SC Paderborn 07", "帕德博恩"),
    ("FC Schalke 04", "沙尔克04"),
    ("SG Dynamo Dresden", "德累斯顿"),
    ("Arminia Bielefeld", "比勒费尔德"),
    ("Darmstadt 98", "达姆施塔特"),
    ("Hannover 96", "汉诺威96"),
    ("Karlsruher SC", "卡尔斯鲁厄"),
    ("1. FC Magdeburg", "马格德堡"),
    ("SV 07 Elversberg", "埃尔弗斯贝格"),
    ("SC Freiburg", "弗赖堡"),
    ("FC St. Pauli", "圣保利"),
    ("1. FC Heidenheim", "海登海姆"),
    ("SV Werder Bremen", "云达不来梅"),
    ("Eintracht Frankfurt", "法兰克福"),
    ("Borussia M'gladbach", "门兴"),
    ("1. FC Union Berlin", "柏林联合"),
    ("Bayer 04 Leverkusen", "勒沃库森"),
    ("TSG Hoffenheim", "霍芬海姆"),
    ("RB Leipzig", "莱比锡RB"),
    ("FC Augsburg", "奥格斯堡"),
    ("VfB Stuttgart", "斯图加特"),
    ("Borussia Dortmund", "多特蒙德"),
    ("1. FSV Mainz 05", "美因茨"),
    ("1. FC Köln", "科隆"),
    ("Hamburger SV", "汉堡"),
    ("Fortuna Düsseldorf", "杜塞尔多夫"),
    ("Hertha BSC", "柏林赫塔"),
    ("Eintracht Braunschweig", "布伦瑞克"),
    ("VfL Bochum 1848", "波鸿"),
    ("Holstein Kiel", "基尔"),
    ("1. FC Nürnberg", "纽伦堡"),
    ("SV Waldhof Mannheim", "曼海姆"),
    ("TSV 1860 München", "慕尼黑1860"),
    ("F.C. Hansa Rostock", "罗斯托克"),
    ("Energie Cottbus", "科特布斯"),
    ("VfL Osnabrück", "奥斯纳布吕克"),
    ("Alemannia Aachen", "亚琛"),
    ("MSV Duisburg", "杜伊斯堡"),
    ("SSV Jahn Regensburg", "雷根斯堡"),
    ("SSV Ulm 1846", "乌尔姆"),
    ("FC Ingolstadt 04", "因戈尔施塔特"),
    ("SV Wehen Wiesbaden", "韦恩"),
    ("Preußen Münster", "普鲁士明斯特"),
    ("SC Verl", "费尔"),
    ("1. FC Saarbrücken", "萨尔布吕肯"),
    ("Erzgebirge Aue", "奥厄"),
    ("1. FC Kaiserslautern", "凯泽斯劳滕"),
    ("TSV Havelse", "哈弗尔塞"),
    ("FC Viktoria Köln", "科隆维多利亚"),
    ("Rot-Weiss Essen", "红白埃森"),
    ("Borussia Dortmund II", "多特蒙德B队"),
    ("VfB Stuttgart II", "斯图加特B队"),
    ("TSG Hoffenheim II", "霍芬海姆B队"),
    ("SV Sandhausen", "桑德豪森"),
    ("SC Verl", "费尔"),
    ("1. FC Schweinfurt 05", "施韦因富特"),
    ("Eintracht Frankfurt II", "法兰克福B队"),
    ("Mainz 05 II", "美因茨B队"),
    # -- 荷甲/荷乙 --
    ("AFC Ajax", "阿贾克斯"),
    ("Willem II Tilburg", "威廉二世"),
    ("NEC Nijmegen", "奈梅亨"),
    ("Heracles Almelo", "赫拉克勒斯"),
    ("Sparta Rotterdam", "鹿特丹斯巴达"),
    ("PSV Eindhoven", "埃因霍温"),
    ("PEC Zwolle", "兹沃勒"),
    ("AZ Alkmaar", "阿尔克马尔"),
    ("SC Heerenveen", "海伦芬"),
    ("Feyenoord", "费耶诺德"),
    ("FC Twente", "特温特"),
    ("Go Ahead Eagles", "前进之鹰"),
    ("Excelsior", "精英"),
    ("FC Groningen", "格罗宁根"),
    ("Fortuna Sittard", "锡塔德幸运"),
    ("NAC Breda", "布雷达"),
    ("Almere City FC", "阿尔梅勒城"),
    ("RKC Waalwijk", "瓦尔韦克"),
    ("SC Telstar", "特尔斯塔"),
    ("FC Den Bosch", "登博斯"),
    ("De Graafschap", "格拉夫夏普"),
    ("Roda JC Kerkrade", "罗达JC"),
    ("MVV Maastricht", "马斯特里赫特"),
    ("FC Eindhoven", "埃因霍温FC"),
    ("VVV-Venlo", "芬洛"),
    ("FC Emmen", "埃门"),
    ("Helmond Sport", "海尔蒙德体育"),
    ("ADO Den Haag", "海牙"),
    ("TOP Oss", "TOP奥斯"),
    ("Jong Ajax", "阿贾克斯B队"),
    ("Jong PSV", "埃因霍温B队"),
    ("Jong AZ", "阿尔克马尔B队"),
    ("Jong FC Utrecht", "乌得勒支B队"),
    # -- 比利时 --
    ("KAA Gent", "根特"),
    ("Club Brugge KV", "布鲁日"),
    ("Royale Union Saint-Gilloise", "圣吉罗斯"),
    ("Sint-Truidense VV", "圣图尔登"),
    ("KVC Westerlo", "韦斯特洛"),
    ("KRC Genk", "亨克"),
    ("RC Sporting Charleroi", "沙勒罗瓦"),
    ("Cercle Brugge", "色格拉布鲁日"),
    ("K. Beerschot V.A.", "比尔肖特"),
    ("SV Zulte Waregem", "聚尔特"),
    ("RAAL La Louvière", "拉卢维耶尔"),
    ("RFC Liège", "列日FC"),
    ("Patro Eisden Maasmechelen", "帕特罗艾斯登"),
    ("Lommel SK", "洛默尔"),
    ("KV Oostende", "奥斯坦德"),
    ("Royal Antwerp FC", "安特卫普"),
    ("KV Mechelen", "梅赫伦"),
    ("OH Leuven", "奥哈鲁汶"),
    ("KMSK Deinze", "丹泽"),
    ("FCV Dender EH", "登德尔"),
    ("Lierse Kempenzonen", "利尔斯"),
    # -- 葡萄牙 --
    ("Casa Pia", "卡萨皮亚"),
    ("SC Farense", "法伦斯"),
    ("Portimonense", "波尔蒂芒人"),
    ("Paços de Ferreira", "帕索斯"),
    ("Estoril Praia", "埃斯托里尔"),
    ("Sporting", "葡萄牙体育"),
    ("Famalicão", "法马利康"),
    ("Sporting Braga", "布拉加"),
    ("FC Arouca", "阿罗卡"),
    ("CD Nacional", "国民"),
    ("Santa Clara", "圣克拉拉"),
    ("Rio Ave", "里奥阿维"),
    ("CF Estrela Amadora", "埃斯特雷拉"),
    ("Tondela", "通德拉"),
    ("Gil Vicente", "吉尔维森特"),
    ("Vitória SC", "吉马良斯"),
    ("Benfica", "本菲卡"),
    ("FC Porto", "波尔图"),
    ("Moreirense", "莫雷伦斯"),
    ("Marítimo", "马里迪莫"),
    ("Leixões SC", "莱索斯"),
    ("Chaves", "查维斯"),
    ("Feirense", "费伦斯"),
    ("Penafiel", "佩纳菲耶尔"),
    ("União Leiria", "莱里亚联"),
    ("FC Alverca", "阿尔维卡"),
    ("Lusitânia Lourosa", "卢西塔尼亚"),
    ("Vizela", "维泽拉"),
    ("Académico Viseu FC", "维塞乌"),
    ("UD Oliveirense", "奥利维伦斯"),
    ("AVS - Futebol SAD", "AVS"),
    ("Torreense", "托伦斯"),
    ("Felgueiras", "费尔盖拉斯"),
    ("Associação Académica de Coimbra", "科英布拉大学"),
    ("Belenenses", "贝伦人"),
    ("C.F. Os Belenenses", "贝伦人"),
    ("Benfica B", "本菲卡B队"),
    ("Sporting CP B", "葡萄牙体育B队"),
    ("FC Porto B", "波尔图B队"),
    # -- 挪威 --
    ("SK Brann", "布兰"),
    ("Rosenborg BK", "罗森博格"),
    ("Vålerenga IF", "瓦勒伦加"),
    ("Aalesunds FK", "奥勒松"),
    ("KFUM Oslo", "奥斯陆KFUM"),
    ("Fredrikstad FK", "腓特烈斯塔"),
    ("HamKam", "汉坎"),
    ("Tromsø IL", "特罗姆瑟"),
    ("Sarpsborg 08", "萨尔普斯堡"),
    ("Bodø/Glimt", "博德闪耀"),
    ("Lillestrøm SK", "利勒斯特罗姆"),
    ("Viking FK", "维京"),
    ("Molde FK", "莫尔德"),
    ("Odds BK", "奥德"),
    ("Moss FK", "莫斯"),
    ("Kristiansund BK", "克里斯蒂安松"),
    ("Sandefjord Fotball", "桑讷菲尤尔"),
    ("Ranheim IL", "兰海姆"),
    ("Bryne FK", "布吕讷"),
    ("Egersund", "埃格尔松"),
    ("Kongsvinger", "孔斯温厄尔"),
    ("Raufoss", "劳福斯"),
    ("Strømmen IF", "斯特勒门"),
    ("Åsane", "阿萨内"),
    ("Strømsgodset", "斯特罗姆加斯特"),
    ("Stabæk Fotball", "斯塔贝克"),
    ("Sogndal IL", "松达尔"),
    ("Sandnes Ulf", "桑内斯乌尔夫"),
    ("Lyn FK", "林恩"),
    ("Hødd IL", "赫德"),
    ("Haugesund", "海于格松"),
    ("Sønderjyske Fodbold", "桑德捷斯基"),
    ("Viborg FF", "维堡"),
    ("Silkeborg IF", "锡尔克堡"),
    ("Randers FC", "兰德斯"),
    # -- 瑞典 --
    ("IFK Värnamo", "韦纳穆"),
    ("Landskrona BoIS", "兰斯克鲁纳"),
    ("IFK Norrköping", "北雪平"),
    ("GIF Sundsvall", "松兹瓦尔"),
    ("Helsingborgs IF", "赫尔辛堡"),
    ("Varbergs BoIS", "瓦尔贝里"),
    ("Örebro SK", "厄勒布鲁"),
    ("IK Brage", "布拉格"),
    ("United IK Nordic", "联队诺迪克"),
    ("IK Oddevold", "奥德沃尔德"),
    ("Östers IF", "厄斯特斯"),
    ("Östersunds FK", "厄斯特松德"),
    ("Västerås SK", "韦斯特罗斯"),
    ("Degerfors IF", "代格福什"),
    ("BK Häcken", "赫根"),
    ("Malmö FF", "马尔默"),
    ("GAIS", "加尔斯"),
    ("AIK", "索尔纳"),
    ("IF Elfsborg", "埃尔夫斯堡"),
    ("IFK Göteborg", "哥德堡"),
    ("IK Sirius", "天狼星"),
    ("Hammarby IF", "哈马比"),
    ("Mjällby AIF", "米亚尔比"),
    ("IF Brommapojkarna", "布洛马波卡纳"),
    ("Örgryte IS", "奥格里特"),
    ("Falkenbergs FF", "法尔肯贝里"),
    ("Ljungskile SK", "永斯基"),
    ("Norrby IF", "诺尔比"),
    # -- 丹麦 --
    ("FC Midtjylland", "中日德兰"),
    ("AGF", "奥胡斯"),
    ("FC København", "哥本哈根"),
    ("FC Fredericia", "弗雷德里西亚"),
    ("Odense Boldklub", "欧登塞"),
    ("Vejle", "瓦埃勒"),
    ("FC Nordsjælland", "北西兰"),
    ("Brøndby IF", "布隆德比"),
    ("AaB", "奥尔堡"),
    ("Lyngby BK", "灵比"),
    ("FC Helsingør", "赫尔辛格"),
    ("Hvidovre IF", "维兹奥勒"),
    ("Kolding IF", "科灵"),
    ("Esbjerg fB", "埃斯比约"),
    ("HB Køge", "克厄"),
    ("Vendsyssel FF", "文德斯尔"),
    ("AC Horsens", "霍森斯"),
    # -- 芬兰 --
    ("AC Oulu", "奥卢"),
    ("SJK Akatemia", "SJK阿卡泰米亚"),
    ("IFK Mariehamn", "玛丽港"),
    ("FC Lahti", "拉赫蒂"),
    ("VPS", "瓦萨"),
    ("FF Jaro", "耶罗"),
    ("Jippo Joensuu", "约恩苏吉波"),
    ("KäPa", "卡帕"),
    ("FC Haka", "哈卡"),
    ("KuPS", "库普斯"),
    ("Inter Turku", "图尔库国际"),
    ("PK-35", "PK-35"),
    ("EIF", "EIF"),
    ("JäPS", "耶普斯"),
    ("KTP", "科特卡"),
    ("HJK", "赫尔辛基"),
    ("Ilves", "伊尔韦斯"),
    ("TPS", "图尔库"),
    ("Honka", "洪卡"),
    ("Vaajakoski", "瓦亚科斯基"),
    ("KPV", "科科拉"),
    # -- 希腊 --
    ("AEK Athens", "雅典AEK"),
    ("Panathinaikos", "帕纳辛奈科斯"),
    ("Aris Thessaloniki", "阿里斯"),
    ("OFI Crete", "OFI克里特"),
    ("Panserraikos", "潘塞莱科斯"),
    ("Asteras Aktor", "阿斯特拉斯"),
    ("AE Larisa", "拉里萨"),
    ("NPS Volos", "沃洛斯"),
    ("APO Levadiakos", "莱瓦迪亚科斯"),
    ("AE Kifisia", "基菲夏"),
    ("Atromitos Athens", "阿特罗米托斯"),
    ("Olympiacos FC", "奥林匹亚科斯"),
    ("PAOK", "塞萨洛尼基"),
    ("Panetolikos", "帕内托利科斯"),
    ("PAS Giannina", "约阿尼纳"),
    ("Ionikos", "伊奥尼科斯"),
    ("Lamia", "拉米亚"),
    ("Kallithea", "卡利地亚"),
    ("Egaleo", "埃加莱奥"),
    ("Ilioupoli", "伊柳波利"),
    ("Kalamata", "卡拉马塔"),
    # -- 土耳其 --
    ("Antalyaspor", "安塔利亚体育"),
    ("Trabzonspor", "特拉布宗体育"),
    ("Kasımpaşa", "卡辛帕萨"),
    ("Fenerbahçe", "费内巴切"),
    ("Samsunspor", "萨姆松体育"),
    ("Gaziantep FK", "加济安泰普"),
    ("Alanyaspor", "阿拉尼亚体育"),
    ("Konyaspor", "科尼亚体育"),
    ("Göztepe", "格兹泰佩"),
    ("Kocaelispor", "科贾埃利体育"),
    ("Başakşehir FK", "巴萨克赛尔"),
    ("Beşiktaş", "贝西克塔斯"),
    ("Galatasaray", "加拉塔萨雷"),
    ("Çaykur Rizespor", "里泽体育"),
    ("Fatih Karagümrük", "法提赫卡拉古姆鲁克"),
    ("Eyüpspor", "埃尤普体育"),
    ("Kayserispor", "开塞利体育"),
    ("Adana Demirspor", "阿达纳德米尔体育"),
    ("Ankaragücü", "安卡拉古库"),
    ("Ümraniyespor", "于姆拉尼耶体育"),
    ("Pendikspor", "彭迪克体育"),
    ("İstanbulspor", "伊斯坦布尔体育"),
    ("Bodrumspor", "博德鲁姆体育"),
    ("Sivasspor", "锡瓦斯体育"),
    # -- 捷克 --
    ("AC Sparta Praha", "布拉格斯巴达"),
    ("SK Slavia Praha", "布拉格斯拉维亚"),
    ("FK Jablonec", "亚布洛内茨"),
    ("FC Silon Táborsko", "塔博尔斯科"),
    ("Baník Ostrava", "俄斯特拉发"),
    ("SK Líšeň", "利森"),
    ("Viktoria Plzeň", "比尔森胜利"),
    ("FC Hradec Králové", "赫拉德茨"),
    ("FC Slovan Liberec", "利贝雷茨"),
    ("FK Teplice", "特普利采"),
    ("FK Pardubice", "帕尔杜比采"),
    ("MFK Karviná", "卡尔维纳"),
    ("Bohemians Praha 1905", "波希米亚人"),
    ("FC Fastav Zlín", "兹林"),
    ("MFK Frýdek-Místek", "弗里代克"),
    ("FK Dukla Praha", "杜克拉布拉格"),
    ("Sigma Olomouc", "奥洛穆茨"),
    ("MFK Chrudim", "赫鲁迪姆"),
    ("FK Mladá Boleslav", "姆拉达博莱斯拉夫"),
    ("FK Varnsdorf", "瓦尔恩斯多夫"),
    ("FC Zbrojovka Brno", "布尔诺"),
    ("SK Dynamo České Budějovice", "布杰约维采迪纳摩"),
    # -- 瑞士 --
    ("FC Lugano", "卢加诺"),
    ("Young Boys", "伯尔尼年轻人"),
    ("FC St. Gallen 1879", "圣加仑"),
    ("FC Aarau", "阿劳"),
    ("FC Winterthur", "温特图尔"),
    ("FC Zürich", "苏黎世"),
    ("FC Lausanne-Sport", "洛桑体育"),
    ("FC Thun", "图恩"),
    ("Basel", "巴塞尔"),
    ("FC Sion", "锡永"),
    ("Servette FC", "塞尔维特"),
    ("FC Luzern", "卢塞恩"),
    ("Yverdon-Sport FC", "伊韦尔东"),
    ("Neuchâtel Xamax", "纳沙泰尔"),
    ("FC Vaduz", "瓦杜兹"),
    ("FC Wil 1900", "维尔"),
    ("FC Rapperswil-Jona", "拉珀斯维尔"),
    ("FC Stade-Lausanne-Ouchy", "洛桑奥奇"),
    ("Stade Nyonnais", "尼永"),
    ("AC Bellinzona", "贝林佐纳"),
    ("Étoile Carouge FC", "卡鲁日星辰"),
    ("FC Schaffhausen", "沙夫豪森"),
    ("FC Bulle", "布勒"),
    ("FC Kriens", "克伦斯"),
    ("SC Cham", "查姆"),
    # -- 奥地利 --
    ("SK Rapid Wien", "维也纳快速"),
    ("Red Bull Salzburg", "萨尔茨堡红牛"),
    ("SK Sturm Graz", "格拉茨风暴"),
    ("Austria Wien", "维也纳奥地利"),
    ("TSV Hartberg", "哈特贝格"),
    ("LASK", "林茨"),
    ("WSG Tirol", "蒂罗尔"),
    ("Grazer AK 1902", "格拉茨AK"),
    ("Austria Klagenfurt", "克拉根福奥地利"),
    ("FC Blau Weiss Linz", "蓝白林茨"),
    ("SC Rheindorf Altach", "阿尔塔奇"),
    ("Wolfsberger AC", "沃尔夫斯贝格"),
    ("Floridsdorfer AC", "弗洛里茨多夫"),
    ("FC Liefering", "列弗宁"),
    ("Kapfenberger SV", "卡芬堡"),
    ("SKU Amstetten", "阿姆施泰滕"),
    ("First Vienna", "第一维也纳"),
    ("SC Austria Lustenau", "卢斯特瑙"),
    ("Schwarz-Weiß Bregenz", "布雷根茨"),
    ("Austria Salzburg", "萨尔茨堡奥地利"),
    ("Young Violets Austria Wien", "维也纳奥地利青年"),
    ("Admira Wacker", "阿德米拉"),
    ("SKN St. Pölten", "圣珀尔滕"),
    ("Rapid Wien II", "维也纳快速B队"),
    ("FC Hertha Wels", "赫塔韦尔斯"),
    # -- 克罗地亚 --
    ("HNK Hajduk Split", "哈伊杜克"),
    ("NK Osijek", "奥西耶克"),
    ("NK Lokomotiva Zagreb", "萨格勒布火车头"),
    ("NK Istra 1961", "伊斯特拉1961"),
    ("HNK Gorica", "戈里察"),
    ("NK Slaven Belupo", "斯拉文贝卢波"),
    ("HNK Vukovar 1991", "武科瓦尔1991"),
    ("GNK Dinamo Zagreb", "萨格勒布迪纳摩"),
    ("NK Dubrava", "杜布拉瓦"),
    ("NK Rijeka", "里耶卡"),
    ("NK Varaždin", "瓦拉日丁"),
    # -- 塞尔维亚 --
    ("FK Radnički Niš", "尼什工人"),
    ("FK Mladost Lučani", "卢查尼青年"),
    ("FK IMT Beograd", "贝尔格莱德IMT"),
    ("FK Radnički 1923", "克拉古耶瓦茨工人"),
    ("OFK Beograd", "贝尔格莱德OFK"),
    ("FK Novi Pazar", "新帕扎尔"),
    ("FK Čukarički", "丘卡里奇基"),
    ("FK Spartak Subotica", "苏博蒂察斯巴达克"),
    ("FK Javor Ivanjica", "伊万尼察雅沃尔"),
    ("FK TSC Bačka Topola", "巴奇卡托波拉"),
    ("FK Napredak Kruševac", "克鲁舍瓦茨进步"),
    ("FK Radnik Surdulica", "苏尔杜利察工人"),
    ("FK Crvena zvezda", "贝尔格莱德红星"),
    ("FK Železničar Pančevo", "潘切沃铁路工"),
    ("FK Partizan", "贝尔格莱德游击"),
    ("FK Vojvodina", "伏伊伏丁那"),
    ("FK Voždovac", "沃日多瓦茨"),
    ("FK Javor Matis", "雅沃尔马蒂斯"),
    ("FK Tekstilac Odžaci", "泰克斯蒂拉茨"),
    ("FK Jedinstvo Ub", "乌布联合"),
    # -- 斯洛伐克 --
    ("ŠK Slovan Bratislava", "布拉迪斯拉发"),
    ("DAC 1904", "多瑙斯特雷达"),
    ("MŠK Žilina", "日利纳"),
    ("MFK Skalica", "斯卡利察"),
    ("AS Trenčín", "特伦钦"),
    ("FC Spartak Trnava", "特尔纳瓦斯巴达克"),
    ("FC Košice", "科希策"),
    ("MFK Zemplín Michalovce", "米哈洛夫采"),
    ("FK Železiarne Podbrezová", "波德布雷佐瓦"),
    ("MFK Ružomberok", "鲁容贝罗克"),
    ("1. FC Tatran Prešov", "普雷绍夫"),
    ("FK Dukla Banská Bystrica", "班斯卡比斯特里察"),
    ("FC ViOn Zlaté Moravce", "兹拉特莫拉夫采"),
    ("FK Senica", "塞尼察"),
    ("MFK Tatran Liptovský Mikuláš", "利普托夫斯基米库拉什"),
    # -- 斯洛文尼亚 --
    ("NK Nafta Lendava 1903", "伦达瓦石油"),
    ("NK Olimpija Ljubljana", "卢布尔雅那奥林匹亚"),
    ("NŠ Mura", "穆拉"),
    ("NK Celje", "采列"),
    ("FC Koper", "科佩尔"),
    ("NK Aluminij Kidričevo", "基德里切沃铝业"),
    ("Kalcer Radomlje", "拉多姆列"),
    ("ND Primorje", "普里莫列"),
    ("NK Maribor", "马里博尔"),
    ("NK Domžale", "多姆扎莱"),
    ("NK Bravo", "布拉沃"),
    ("NK Rogaška", "罗加什卡"),
    # -- 乌克兰 --
    ("Dynamo Kyiv", "基辅迪纳摩"),
    ("Polissya Zhytomyr", "日托米尔波利西亚"),
    ("Veres Rivne", "里夫内维雷斯"),
    ("Obolon Kyiv", "基辅奥博隆"),
    ("Zoria Luhansk", "卢甘斯克黎明"),
    ("Rukh Lviv", "利沃夫鲁赫"),
    ("FC Kryvbas Kryvyi Rih", "克里夫巴斯"),
    ("Shakhtar Donetsk", "顿涅茨克矿工"),
    ("Kolos Kovalivka", "科瓦利夫卡科洛斯"),
    ("LNZ Cherkasy", "切尔卡瑟LNZ"),
    ("SC Poltava", "波尔塔瓦"),
    ("Metalist 1925", "1925哈尔科夫冶金"),
    ("Ahrobiznes Volochysk", "沃洛奇斯克农业"),
    ("FC Livyi Bereh Kyiv", "基辅左岸"),
    ("Kudrivka", "库德里夫卡"),
    ("Oleksandria", "亚历山德里亚"),
    ("Vorskla Poltava", "沃尔斯克拉"),
    ("FC Minai", "米奈"),
    ("Chornomorets Odesa", "敖德萨黑海人"),
    ("SK Dnipro-1", "第聂伯罗1"),
    ("FC Lviv", "利沃夫"),
    # -- 波兰 --
    ("MZKS Arka Gdynia", "阿尔卡格丁尼亚"),
    ("KS Lechia Gdańsk", "格但斯克莱希亚"),
    ("Piast Gliwice", "皮亚斯特"),
    ("Radomiak Radom", "拉多米亚克"),
    ("Wisła Płock", "普沃茨克维斯瓦"),
    ("MKS Korona Kielce", "凯尔采科罗纳"),
    ("Zagłębie Lubin", "卢宾扎格勒比"),
    ("GKS Katowice", "卡托维兹"),
    ("Motor Lublin", "卢布林摩托"),
    ("Jagiellonia Białystok", "比亚韦斯托克雅盖隆"),
    ("Legia Warsaw", "华沙莱吉亚"),
    ("Lech Poznań", "波兹南莱赫"),
    ("Raków Częstochowa", "琴斯托霍瓦拉科夫"),
    ("Pogoń Szczecin", "什切青波贡"),
    ("Górnik Zabrze", "扎布热矿工"),
    ("Warta Poznań", "波兹南瓦塔"),
    ("Stal Mielec", "梅莱茨钢铁"),
    ("Śląsk Wrocław", "弗罗茨瓦夫斯拉斯克"),
    ("Widzew Łódź", "罗兹维泽夫"),
    ("Cracovia", "克拉科维亚"),
    ("Wisła Kraków", "克拉科夫维斯瓦"),
    ("Górnik Łęczna", "文奇纳矿工"),
    ("Miedź Legnica", "莱格尼察梅兹"),
    ("Chrobry Głogów", "格沃古夫赫罗布里"),
    ("Podbeskidzie Bielsko-Biała", "别尔斯科-比亚拉"),
    ("Ruch Chorzów", "霍茹夫运动"),
    ("Znicz Pruszków", "普鲁什库夫兹尼茨"),
    ("Polonia Warsaw", "华沙波兰人"),
    # -- 匈牙利 --
    ("Debreceni VSC", "德布勒森"),
    ("Ferencváros TC", "费伦茨瓦罗斯"),
    ("Diósgyőri VTK", "迪欧斯捷尔"),
    ("Kisvárda FC", "小瓦尔道"),
    ("Puskás Akadémia", "普斯卡什学院"),
    ("Zalaegerszegi TE", "佐洛埃格塞格"),
    ("Paksi FC", "帕克斯"),
    ("Újpest", "乌伊佩斯特"),
    ("ETO FC Győr", "杰尔ETO"),
    ("Nyiregyháza Spartacus", "尼赖吉哈佐"),
    ("MTK Budapest", "布达佩斯MTK"),
    ("Kazincbarcikai SC", "考津茨巴尔齐考"),
    ("Fehérvár FC", "费黑尔瓦"),
    ("Budapest Honvéd", "布达佩斯守卫"),
    ("Mezőkövesd", "迈泽克韦什德"),
    ("Vasas FC", "瓦萨斯"),
    ("Gyirmót FC", "吉尔莫特"),
    ("Békéscsaba", "贝凯什乔包"),
    # -- 罗马尼亚 --
    ("FC Dinamo București", "布加勒斯特迪纳摩"),
    ("FC Farul Constanța", "康斯坦察法鲁尔"),
    ("FC Hermannstadt", "赫尔曼施塔特"),
    ("FC Petrolul Ploieşti", "普洛耶什蒂石油"),
    ("AFC Unirea 04 Slobozia", "斯洛博齐亚联"),
    ("Universitatea Craiova", "克拉约瓦大学"),
    ("FCSB", "布加勒斯特星"),
    ("FC Voluntari", "沃伦塔里"),
    ("FC Botoșani", "博托沙尼"),
    ("FC Metaloglobus București", "布加勒斯特金属"),
    ("FC Rapid București", "布加勒斯特快速"),
    ("SC Oțelul Galați", "加拉茨钢铁"),
    ("FC Argeș Pitești", "阿尔杰什"),
    ("UTA Arad", "阿拉德UTA"),
    ("Sepsi OSK", "塞普西"),
    ("FC U Craiova", "克拉约瓦大学1948"),
    ("ACS Viitorul Târgu Jiu", "特尔古日乌未来"),
    ("CSM Politehnica Iași", "雅西波利泰尼卡"),
    ("SCM Gloria Buzău", "布泽乌荣耀"),
    ("CS Mioveni", "米奥韦尼"),
    ("Universitatea Cluj", "克卢日大学"),
    ("CFR Cluj", "克卢日"),
    # -- 保加利亚 --
    ("Ludogorets", "卢多戈雷茨"),
    ("Cherno More Varna", "瓦尔纳黑海"),
    ("Lokomotiv Plovdiv", "普罗夫迪夫火车头"),
    ("FC CSKA 1948 Sofia", "索菲亚中央陆军1948"),
    ("CSKA Sofia", "索菲亚中央陆军"),
    ("Arda Kardzhali", "阿尔达"),
    ("Botev Plovdiv", "普罗夫迪夫博特夫"),
    ("Levski Sofia", "索菲亚列夫斯基"),
    ("PFK Montana 1921", "蒙塔纳"),
    ("FK Dobrudzha Dobrich", "多布里奇"),
    ("Lokomotiv Sofia", "索菲亚火车头"),
    ("Beroe Stara Zagora", "旧扎戈拉贝罗"),
    ("Slavia Sofia", "索菲亚斯拉维亚"),
    ("FK Krumovgrad", "克鲁莫夫格勒"),
    ("FC Hebar Pazardzhik", "赫巴尔帕扎尔吉克"),
    ("FK Spartak Varna", "瓦尔纳斯巴达克"),
    ("Botev Vratsa", "弗拉察博特夫"),
    # -- 俄罗斯 --
    ("FC Spartak Moscow", "莫斯科斯巴达克"),
    ("Rotor Volgograd", "伏尔加格勒"),
    ("Ural Yekaterinburg", "叶卡捷琳堡乌拉尔"),
    ("FC Rostov", "罗斯托夫"),
    ("FC Sochi", "索契"),
    ("CSKA Moscow", "莫斯科中央陆军"),
    ("Rubin Kazan", "喀山红宝石"),
    ("Baltika Kaliningrad", "加里宁格勒"),
    ("Krylya Sovetov Samara", "萨马拉苏维埃之翼"),
    ("FK Krasnodar", "克拉斯诺达尔"),
    ("Dynamo Moscow", "莫斯科迪纳摩"),
    ("Lokomotiv Moscow", "莫斯科火车头"),
    ("Zenit St. Petersburg", "圣彼得堡泽尼特"),
    ("Akhmat Grozny", "格罗兹尼"),
    ("Orenburg", "奥伦堡"),
    ("Pari Nizhny Novgorod", "下诺夫哥罗德"),
    ("Fakel Voronezh", "法克尔沃罗涅日"),
    ("Khimki", "希姆基"),
    ("FC Ufa", "乌法"),
    ("FC Sibir Novosibirsk", "西伯尔新西伯利亚"),
    ("Arsenal Tula", "图拉兵工厂"),
    ("FC Yenisey", "叶尼塞"),
    ("FC Alania Vladikavkaz", "阿拉尼亚"),
    ("FC Neftekhimik Nizhnekamsk", "下卡姆斯克石油"),
    ("FC KAMAZ", "卡马斯"),
    # -- 以色列 --
    ("Maccabi Haifa", "海法马卡比"),
    ("Hapoel Haifa", "海法工人"),
    ("Hapoel Jerusalem", "耶路撒冷工人"),
    ("Hapoel Ironi Kiryat Shmona", "谢莫纳城工人"),
    ("Maccabi Bney Reine", "马卡比雷内"),
    ("Maccabi Tel Aviv", "特拉维夫马卡比"),
    ("Bnei Sakhnin", "萨赫宁"),
    ("Ashdod SC", "阿什杜德"),
    ("Ironi Tiberias", "提比里亚"),
    ("Maccabi Netanya", "内坦亚马卡比"),
    ("Hapoel Tel Aviv", "特拉维夫工人"),
    ("Beitar Jerusalem", "耶路撒冷贝塔"),
    ("Hapoel Petah Tikva", "佩塔提克瓦工人"),
    ("Hapoel Hadera", "哈代拉工人"),
    ("Maccabi Petah Tikva", "佩塔提克瓦马卡比"),
    ("MS Ashdod", "阿什杜德"),
    ("Hapoel Rishon LeZion", "里雄莱锡安工人"),
    ("Hapoel Be'er Sheva", "贝尔谢巴工人"),
    # -- 沙特联赛 --
    ("Al-Shabab", "利雅得青年"),
    ("Al-Taawoun", "塔亚文"),
    ("Damac FC", "达马克"),
    ("Al-Qadsiah", "卡迪西亚"),
    ("Al-Ettifaq", "哈萨征服"),
    ("Al-Fateh", "费哈"),
    ("Al-Okhdood", "阿克胡德"),
    ("Al-Ahli", "阿赫利"),
    ("Al-Hilal", "利雅得新月"),
    ("Al-Nassr", "利雅得胜利"),
    ("Al-Ittihad", "吉达联合"),
    ("Al-Raed", "拉德"),
    ("Al-Fayha", "费哈"),
    ("Abha", "艾卜哈"),
    ("Al-Tai", "泰伊"),
    ("Al-Adalah", "阿拉达"),
    ("Al-Khaleej", "海湾"),
    ("Al-Wehda", "瓦赫达"),
    ("Al-Riyadh", "利雅得"),
    ("Al-Najma SC", "纳杰马"),
    # -- 卡塔尔联赛 --
    ("Al-Sadd", "萨德"),
    ("Al-Wakrah", "沃克拉"),
    ("Al-Rayyan", "赖扬"),
    ("Umm-Salal SC", "乌姆沙拉尔"),
    ("Qatar SC", "卡塔尔SC"),
    ("Al-Gharafa", "加拉法"),
    ("Al-Ahli Doha", "多哈阿赫利"),
    ("Al-Duhail", "杜海勒"),
    ("Al-Shahaniya", "沙哈尼亚"),
    ("Al-Arabi Doha", "多哈阿拉伯人"),
    ("Al-Markhiya", "马尔希亚"),
    ("Muaither SC", "穆埃瑟"),
    # -- 阿联酋联赛 --
    ("Al Wasl", "瓦塞尔"),
    ("Al-Ain FC", "艾因"),
    ("Al-Nasr SC", "纳斯尔"),
    ("Sharjah FC", "沙迦"),
    ("Al-Wahda FC", "瓦赫达"),
    ("Shabab Al-Ahli", "青年国民"),
    ("Ittihad Kalba", "伊蒂哈德卡尔巴"),
    ("Baniyas Club", "巴尼亚斯"),
    ("Dibba Al-Hisn", "迪巴阿尔希森"),
    ("Emirates Club", "酋长俱乐部"),
    ("Khor Fakkan", "豪尔法坎"),
    ("Al-Bataeh", "巴塔赫"),
    ("Ajman Club", "阿治曼"),
    ("Hatta Club", "哈塔"),
    # -- 韩K2/低级别 --
    ("Siheung Citizen FC", "始兴市民"),
    ("Pocheon FC", "抱川FC"),
    ("Daejeon Korail FC", "大田铁道"),
    ("Mokpo City FC", "木浦市"),
    ("Changwon City FC", "昌原市"),
    ("Yangpyeong FC", "杨平FC"),
    ("Chuncheon Citizen FC", "春川市民"),
    ("Yeoju FC", "骊州FC"),
    ("Pyeongchang United FC", "平昌联"),
    ("Goyang Citizen FC", "高阳市民"),
    ("Goyang KH FC", "高阳KH"),
    ("Sejong SA FC", "世宗SA"),
    ("Geoje Citizen FC", "巨济市民"),
    ("Jeonju Citizen FC", "全州市民"),
    ("Namdong FC", "南洞FC"),
    ("Dangjin Citizen FC", "唐津市民"),
    ("Pyeongtaek FC", "平泽FC"),
    ("Ulsan Citizen FC", "蔚山市民"),
    ("Busan Transportation Corp.", "釜山交通公社"),
    # -- 日本J3/低级别 --
    ("Criacao Shinjuku", "克利亚松新宿"),
    ("Tokyo 23 FC", "东京23"),
    ("Tonan Maebashi", "图南前桥"),
    ("Vonds Ichihara", "本德市原"),
    ("Atletico Suzuka Club", "铃鹿竞技"),
    ("Asuka FC", "飞鸟FC"),
    ("FC Kariya", "刈谷FC"),
    ("Wyvern Aichi", "翼龙爱知"),
    ("FC Ise-Shima", "伊势志摩FC"),
    ("Chukyo University", "中京大学"),
    ("Bannyu Chukyo University", "中京大学"),
    ("Suzuka Point Getters", "铃鹿得分手"),
    ("Veertien Mie", "三重维尔蒂恩"),
    ("Kariya FC", "刈谷FC"),
    ("Maruyasu Okazaki", "丸安冈崎"),
    ("FC Gifu Second", "岐阜FC二队"),
    ("Mino FC", "美濃FC"),
    ("Briobecca Urayasu", "浦安布里奥贝卡"),
    ("YSCC Yokohama", "YSCC横滨"),
    ("Toho Titanium", "东邦钛"),
    ("Tokyo United FC", "东京联"),
    ("Shinagawa CC", "品川CC"),
    ("Rikuo FC", "利库奥FC"),
    ("Nankatsu SC", "南葛SC"),
    ("Toho Titanium SC", "东邦钛SC"),
    ("Tsukuba FC", "筑波FC"),
    ("Aries Tokyo FC", "白羊东京FC"),
    ("Viancone Fukushima", "福岛维安科内"),
    ("Bandits Iwate", "岩手匪徒"),
    ("FC Morioka", "盛冈FC"),
    ("Iwate Grulla Morioka", "岩手盛冈双鹤"),
    ("Cobaltore Onagawa", "小名滨科巴尔特"),
    ("Shichigahama SC", "七滨SC"),
    ("Sendai University", "仙台大学"),
    ("Blancdieu Hirosaki", "弘前白帝"),
    ("Fuji University", "富士大学"),
    ("Niigata University H&W", "新潟大学"),
    ("Japan Soccer College", "日本足球学院"),
    ("Toyama Shinjo Club", "富山新城俱乐部"),
    ("Artista Tomi", "艺术大师东美"),
    ("Fukui United FC", "福井联"),
    ("Sakai Phoenix", "堺凤凰"),
    ("Lagend Shiga", "传奇滋贺"),
    ("AS Laranja Kyoto", "京都AS"),
    ("Ococias Kyoto AC", "京都奥科西亚斯"),
    ("Amitie SC", "友谊SC"),
    ("Kansai University", "关西大学"),
    ("Cento Cuore Harima", "森特库雷哈丽玛"),
    ("Takasago Mineiro", "高砂米内罗"),
    ("FC Basara Hyogo", "巴萨拉兵库"),
    ("Kobe FC", "神户FC"),
    ("FC Awaji", "淡路FC"),
    ("Kansai FC", "关西FC"),
    ("St. Andrew's FC", "圣安德鲁FC"),
    ("Tottori Koyo", "鸟取光阳"),
    ("Mitsubishi Mizushima", "三菱水岛"),
    ("Sanyo Electric", "三洋电机"),
    ("Baleine Shimonoseki", "下关鲸"),
    ("Kagawa Next", "香川内斯特"),
    ("FC Tokushima", "德岛FC"),
    ("Kochi University", "高知大学"),
    ("FC Imabari Next", "今治FC未来"),
    ("Nobeoka Agata", "延冈亚加塔"),
    ("Kumamoto Gakuen University", "熊本学园大学"),
    ("J-Lease FC", "J租赁FC"),
    ("Sagamihara University", "相模原大学"),
    ("Kanagawa University", "神奈川大学"),
    ("Kanto Gakuin University", "关东学院大学"),
    ("Toin University of Yokohama", "桐荫横滨大学"),
    ("Sanno University", "产业能率大学"),
    ("Josai University", "城西大学"),
    ("Ryutsu Keizai University", "流通经济大学"),
    ("Toho University", "东邦大学"),
    ("Chiba University", "千叶大学"),
    # -- 英超补充 --
    ("Liverpool FC", "利物浦"),
    ("Chelsea FC", "切尔西"),
    ("Brighton", "布莱顿"),
    ("Tottenham FC", "托特纳姆热刺"),
    ("West Ham", "西汉姆联"),
    ("Liverpool FC Women", "利物浦女足"),
    ("Chelsea FC Women", "切尔西女足"),
    ("Arsenal Women", "阿森纳女足"),
    ("Manchester City Women", "曼城女足"),
    # -- USL 补充 --
    ("Monterey Bay FC", "蒙特雷湾FC"),
    ("Las Vegas Lights FC", "拉斯维加斯之光"),
    ("Orange County SC", "橙县SC"),
    ("Sacramento Republic FC", "萨克拉门托共和"),
    ("Phoenix Rising FC", "凤凰重生"),
    ("New Mexico United", "新墨西哥联"),
    ("El Paso Locomotive FC", "埃尔帕索机车"),
    ("Oakland Roots SC", "奥克兰根"),
    ("FC Tulsa", "塔尔萨"),
    ("San Antonio FC", "圣安东尼奥FC"),
    ("Pittsburgh Riverhounds SC", "匹兹堡河犬"),
    ("Birmingham Legion FC", "伯明翰军团"),
    ("Louisville City FC", "路易斯维尔城"),
    ("Colorado Springs Switchbacks FC", "科罗拉多斯普林斯"),
    ("Indy Eleven", "印第安纳十一人"),
    ("Hartford Athletic", "哈特福德竞技"),
    ("Detroit City FC", "底特律城"),
    ("Miami FC", "迈阿密FC"),
    ("Rhode Island FC", "罗德岛FC"),
    ("Charleston Battery", "查尔斯顿电池"),
    ("Tampa Bay Rowdies", "坦帕湾粗汉"),
    ("Memphis 901 FC", "孟菲斯901"),
    ("Rio Grande Valley FC", "里奥格兰德河谷"),
    ("Loudoun United FC", "劳登联"),
    ("North Carolina FC", "北卡罗来纳FC"),
    ("Forward Madison FC", "麦迪逊前锋"),
    ("Union Omaha SC", "奥马哈联"),
    ("Richmond Kickers", "里士满踢球者"),
    ("Greenville Triumph SC", "格林维尔胜利"),
    ("Chattanooga Red Wolves SC", "查塔努加红狼"),
    ("Tormenta FC", "风暴FC"),
    ("Central Valley Fuego FC", "中央山谷火球"),
    ("Northern Colorado Hailstorm", "北科罗拉多冰雹"),
    ("Charlotte Independence", "夏洛特独立"),
    ("New England Revolution II", "新英格兰革命B队"),
    ("Chicago Fire II", "芝加哥火焰B队"),
    ("Columbus Crew 2", "哥伦布机员B队"),
    ("Philadelphia Union II", "费城联B队"),
    ("Orlando City B", "奥兰多城B队"),
    ("Atlanta United 2", "亚特兰大联2"),
    ("FC Cincinnati 2", "辛辛那提2队"),
    ("New York Red Bulls II", "纽约红牛B队"),
    ("Toronto FC II", "多伦多FCB队"),
    ("Inter Miami CF II", "迈阿密国际B队"),
    ("LA Galaxy II", "洛杉矶银河B队"),
    ("Minnesota United 2", "明尼苏达联2队"),
    ("Sporting Kansas City II", "堪萨斯城体育B队"),
    ("Real Salt Lake Monarchs", "皇家盐湖城君主"),
    ("Portland Timbers 2", "波特兰伐木工B队"),
    ("Seattle Sounders FC 2", "西雅图海湾人B队"),
    ("San Jose Earthquakes II", "圣何塞地震B队"),
    ("Houston Dynamo 2", "休斯顿迪纳摩2队"),
    ("Austin FC II", "奥斯汀FCB队"),
    ("Colorado Rapids 2", "科罗拉多急流2队"),
    ("Vancouver Whitecaps FC 2", "温哥华白帽2队"),
    ("Los Angeles FC 2", "洛杉矶FC2队"),
    ("St. Louis City 2", "圣路易斯城2队"),
    ("Tacoma Defiance", "塔科马抗争"),
    ("Whitecaps FC 2", "白帽FC2队"),
    ("Burning River SC", "燃烧河流"),
    ("Rochester New York FC", "罗切斯特纽约FC"),
    # -- NWSL 女足 --
    ("Orlando Pride", "奥兰多荣耀"),
    ("Racing Louisville", "路易斯维尔竞技"),
    ("Angel City FC", "天使城FC"),
    ("NJ/NY Gotham FC", "哥谭FC"),
    ("Chicago Stars FC", "芝加哥星辰"),
    ("Bay FC", "海湾FC"),
    ("San Diego Wave FC", "圣迭戈波浪"),
    ("Seattle Reign FC", "西雅图君主"),
    ("Kansas City Current", "堪萨斯城潮流"),
    ("Houston Dash", "休斯顿达什"),
    ("Utah Royals FC", "犹他皇家"),
    ("Portland Thorns FC", "波特兰荆棘"),
    ("Washington Spirit", "华盛顿精神"),
    ("North Carolina Courage", "北卡罗来纳勇气"),
    ("Boston Legacy FC", "波士顿传承"),
    ("FC America", "美国FC"),
    ("London City Lionesses", "伦敦城雌狮"),
    # -- 菲律宾 --
    ("Kaya FC-Iloilo", "卡雅伊洛伊洛"),
    ("Stallion Laguna FC", "种马拉古纳"),
    ("Dynamic Herb Cebu", "动态宿务"),
    ("Davao Aguilas", "达沃鹰"),
    ("United City FC", "联合城"),
    ("Maharlika Manila FC", "马哈利卡马尼拉"),
    # -- 缅甸 --
    ("Shan United FC", "掸邦联"),
    ("Yangon United FC", "仰光联"),
    ("Ayeyawady United FC", "伊洛瓦底联"),
    ("Hanthawaddy United FC", "罕塔瓦底联"),
    ("Sagaing United FC", "实皆联"),
    ("Rakhine United FC", "若开联"),
    ("Yadanarbon FC", "亚达纳邦"),
    # -- 伊朗 --
    ("Persepolis FC", "波斯波利斯"),
    ("Esteghlal FC", "德黑兰独立"),
    ("Sepahan FC", "塞帕汉"),
    ("Tractor SC", "拖拉机"),
    ("Foolad FC", "福拉德"),
    ("Gol Gohar Sirjan FC", "戈尔戈哈尔"),
    ("Paykan FC", "佩坎"),
    ("Sanat Naft FC", "石油工业"),
    ("Zob Ahan FC", "卓伯阿汉"),
    ("Mes Rafsanjan FC", "梅斯拉夫桑詹"),
    ("Aluminium Arak FC", "阿拉克铝业"),
    ("Havadar SC", "哈瓦达尔"),
    ("Naft Masjed Soleyman FC", "石油马斯吉德苏莱曼"),
    ("Malavan FC", "马拉万"),
    ("Shahr Khodrou FC", "沙尔赫德罗"),
    ("Saipa FC", "赛帕"),
    ("FC Nassaji Mazandaran", "纳萨吉马赞德兰"),
    ("Kheybar Khorramabad FC", "海巴尔霍拉马巴德"),
    ("F.C. Khoosheh Talai", "黄金矿业"),
    # -- 伊拉克 --
    ("Al-Shorta SC", "警察"),
    ("Al-Quwa Al-Jawiya", "空军"),
    ("Al-Zawraa SC", "扎瓦拉"),
    ("Al-Talaba SC", "学生"),
    ("Erbil SC", "埃尔比勒"),
    ("Naft Al-Wasat SC", "中部石油"),
    ("Al-Najaf FC", "纳杰夫"),
    ("Al-Minaa SC", "米纳"),
    ("Naft Maysan FC", "迈桑石油"),
    ("Al-Qasim SC", "卡西姆"),
    ("Duhok SC", "杜胡克"),
    ("Al-Karkh SC", "卡尔赫"),
    ("Al-Hudood SC", "胡杜德"),
    ("Al-Kahrabaa FC", "电力"),
    ("Zakho FC", "扎胡"),
    ("Amanat Baghdad", "巴格达信托"),
    ("Newroz SC", "内鲁兹"),
    ("Karbalaa FC", "卡尔巴拉"),
    ("Al-Naft SC", "纳夫特"),
    # -- 沙特国王杯/低级别 --
    ("Ohod Club", "奥霍德"),
    ("Hajer Club", "哈杰尔"),
    ("Al-Jabalain", "贾巴兰"),
    ("Al-Batin", "巴廷"),
    ("Al-Safa FC", "萨法"),
    ("Al-Najma", "纳杰马"),
    ("Al-Taraji", "塔拉吉"),
    ("Al-Nojoom", "努朱姆"),
    ("Al-Jeel", "吉尔"),
    ("Al-Rawdhah", "劳达"),
    ("Al-Sahel", "萨赫勒"),
    ("Al-Kholood", "霍鲁德"),
    ("Al-Ain FC (KSA)", "艾因(沙特)"),
    ("Al-Arabi (KSA)", "阿拉伯人(沙特)"),
    ("Al-Qaisumah", "盖苏马"),
    ("Al-Ansar", "安萨尔"),
    # -- 突尼斯联赛 --
    ("Espérance Tunis", "突尼斯希望"),
    ("Club Africain", "非洲人"),
    ("US Monastir", "莫纳斯提尔"),
    ("ES Métlaoui", "梅特劳伊"),
    ("US Ben Guerdane", "本加尔丹"),
    ("CS Sfaxien", "斯法克西恩"),
    ("Étoile Sportive Du Sahel", "沙希尔之星"),
    ("US Ben Guerdane", "本加尔丹"),
    ("Stade Tunisien", "突尼斯体育场"),
    ("Olympique Béja", "贝贾奥林匹克"),
    ("Avenir Sportif De La Marsa", "马尔萨"),
    ("ES Zarzis", "扎尔吉斯"),
    ("AS Soliman", "苏莱曼"),
    ("JS Omrane", "奥姆兰青年"),
    ("JS Kairouanaise", "凯鲁万青年"),
    ("Avenir Sportif De Gabes", "加贝斯未来"),
    ("CA Bizertin", "比塞丁"),
    ("EGS Gafsa", "加夫萨"),
    ("CS Hammam-Lif", "哈马姆利夫"),
    # -- 塞浦路斯联赛 --
    ("APOEL Nicosia", "希腊人竞技"),
    ("AEK Larnaca", "拉纳卡AEK"),
    ("Apollon Limassol", "阿波罗利马索尔"),
    ("AEL Limassol", "AEL利马索尔"),
    ("Omonia Nicosia", "奥莫尼亚"),
    ("Anorthosis Famagusta", "阿诺托西斯"),
    ("Aris Limassol", "阿里斯利马索尔"),
    ("Pafos FC", "帕福斯FC"),
    ("Nea Salamina", "新萨拉米斯"),
    ("Karmiotissa FC", "卡米奥提萨"),
    ("Olympiakos Nicosia", "奥林匹亚科斯尼科西亚"),
    ("Enosis Neon Paralimniou", "帕拉利姆尼"),
    ("Ethnikos Achnas", "阿赫纳国民"),
    ("Akritas Chlorakas", "阿克里塔斯"),
    ("Omonia Aradippou", "奥莫尼亚阿拉迪普"),
    ("Doxa Katokopias", "多克萨"),
    ("ENY Digenis Ypsonas", "伊普索纳斯"),
    ("AEZ Zakakiou", "扎卡基乌"),
    ("Peyia 2014", "佩亚2014"),
    ("PO Xylotymbou", "克西洛廷布"),
    # -- 女足补充 --
    ("London City Lionesses", "伦敦城雌狮"),
    ("Crystal Palace Women", "水晶宫女足"),
    ("Tottenham Hotspur Women", "热刺女足"),
    ("West Ham United Women", "西汉姆联女足"),
    ("Brighton & Hove Albion Women", "布莱顿女足"),
    ("Everton Women", "埃弗顿女足"),
    ("Leicester City Women", "莱斯特城女足"),
    ("Liverpool FC Women", "利物浦女足"),
    ("Manchester City Women", "曼城女足"),
    ("Manchester United Women", "曼联女足"),
    ("Aston Villa Women", "阿斯顿维拉女足"),
    ("Bristol City Women", "布里斯托尔城女足"),
    ("Reading Women", "雷丁女足"),
    ("Birmingham City Women", "伯明翰女足"),
    ("Charlton Athletic Women", "查尔顿女足"),
    ("Racing Club de France", "法兰西竞技"),
    # -- 埃及补充 --
    ("Al Ahly SC", "开罗国民"),
    ("ENPPI Club", "恩皮"),
    ("Haras El Hodoud", "哈拉斯埃尔霍杜德"),
    ("El Entag El Harby", "埃尔恩塔格"),
    ("Wadi Degla FC", "瓦迪德格拉"),
    # -- 约旦 --
    ("Al-Faisaly SC", "费萨利"),
    ("Al-Wehdat SC", "瓦赫达特"),
    ("Al-Hussein SC", "侯赛因"),
    ("Shabab Al-Ordon", "青年约旦"),
    ("Al-Ramtha SC", "拉姆萨"),
    ("Al-Jazeera SC", "杰济拉"),
    ("Sahab SC", "萨哈布"),
    ("Al-Ahli SC", "阿赫利(约旦)"),
    ("Ma'an FC", "马安"),
    ("Al-Salt SC", "萨尔特"),
    ("Al-Baqa'a SC", "巴卡"),
    # -- 黎巴嫩 --
    ("Al-Ahed FC", "阿赫德"),
    ("Nejmeh SC", "星"),
    ("Al-Ansar FC", "安萨尔"),
    ("Safa SC", "萨法"),
    ("Shabab Al-Sahel", "青年海岸"),
    ("Tripoli SC", "的黎波里"),
    ("Al-Akhaa Al-Ahli", "阿哈阿赫利"),
    ("Tadamon Sour SC", "泰达蒙苏尔"),
    ("Bourj FC", "布尔吉"),
    ("Racing Beirut", "贝鲁特竞技"),
    ("Salam Zgharta", "萨拉姆兹加尔塔"),
    # -- 阿曼联赛 --
    ("Al-Seeb SC", "西布"),
    ("Al-Nahda Club", "纳赫达"),
    ("Al-Suwaiq Club", "苏韦克"),
    ("Sohar SC", "苏哈尔"),
    ("Dhofar Club", "佐法尔"),
    ("Muscat Club", "马斯喀特"),
    ("Bahla Club", "巴赫拉"),
    ("Oman Club", "阿曼"),
    ("Al-Rustaq", "鲁斯塔克"),
    ("Al-Khaburah", "哈布拉"),
    ("Ebri Club", "埃布里"),
    ("Sur SC", "苏尔"),
    ("Al-Mussanah", "穆萨纳"),
    ("Fanja SC", "范贾"),
    # -- 巴林联赛 --
    ("Al-Muharraq SC", "穆哈拉克"),
    ("Al-Riffa SC", "里法"),
    ("Al-Khaldiya SC", "哈尔迪亚"),
    ("Manama Club", "麦纳麦"),
    ("East Riffa Club", "东里法"),
    ("Al-Shabbab Club", "沙巴布"),
    ("Al-Hala SC", "哈拉"),
    ("Al-Najma Club", "纳杰马"),
    ("Busaiteen Club", "布赛廷"),
    ("Al-Ahli Club (Manama)", "阿赫利(麦纳麦)"),
    ("Sitra Club", "锡特拉"),
    ("Budaiya Club", "布代亚"),
    ("Malkiya Club", "马尔基亚"),
    ("Qalali Club", "卡拉利"),
    # -- 科威特联赛 --
    ("Kuwait SC", "科威特SC"),
    ("Al-Arabi SC (Kuwait)", "阿拉伯人(科威特)"),
    ("Qadsia SC", "卡迪西亚"),
    ("Al-Salmiyah SC", "萨勒米亚"),
    ("Al-Fahaheel FC", "法哈希尔"),
    ("Al-Nasr SC (Kuwait)", "纳斯尔(科威特)"),
    ("Kazma SC", "卡兹马"),
    ("Al-Jahra SC", "贾赫拉"),
    ("Khaitan FC", "海坦"),
    ("Al-Shabab (Kuwait)", "沙巴布(科威特)"),
    ("Burgan SC", "布尔甘"),
    ("Al-Sahel SC (Kuwait)", "萨赫勒(科威特)"),
    # -- 叙利亚联赛 --
    ("Tishreen SC", "十月"),
    ("Al-Jaish SC (Syria)", "陆军(叙利亚)"),
    ("Al-Wahda SC (Syria)", "瓦赫达(叙利亚)"),
    ("Al-Ittihad SC (Syria)", "伊蒂哈德(叙利亚)"),
    ("Al-Karamah SC", "卡拉马"),
    ("Al-Fotuwa SC", "福图瓦"),
    ("Al-Horriya SC", "自由"),
    ("Jableh SC", "贾布莱"),
    ("Hutteen SC", "胡廷"),
    ("Al-Majd SC", "马吉德"),
    ("Al-Taliya SC", "塔利亚"),
    ("Al-Wathba SC", "瓦特巴"),
    ("Al-Sahel SC (Syria)", "萨赫勒(叙利亚)"),
]

# 当前需要额外覆盖的修正项（英文名和现有中文名不同）
fix_overrides = {
    "Côte d'Ivoire": "科特迪瓦",  # 原来 mapping 中是 Ivory Coast
    "Czechia": "捷克",
    "Türkiye": "土耳其",
    "Fortaleza": "福塔雷萨",
}

# 执行添加
for en_name, cn_name in entries:
    if add(en_name, cn_name):
        added += 1

# 特殊处理：对已有中文键但英文名不同的，加反向条目（如果en_key不存在）
for correct_en, cn in fix_overrides.items():
    k = key_for(correct_en)
    if k not in en_to_cn:
        mapping[cn] = correct_en
        en_to_cn[k] = cn
        cn_keys.add(cn)
        added += 1

# 保存
with open(MAPPING_PATH, 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)

print(f"✅ 新增 {added} 条映射，现有共 {len(mapping)} 条")
